### ISSUE TITLE
@Compare does not support Bean Validation 2.0

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw#1013]
## Description

https://github.com/terasolunaorg/terasoluna-gfw/blob/e37b5ae9cdecd1f29245ddcdfb68b4effc79741c/terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraints/Compare.java#L54-L58

`@Compare` does not support Bean Validation 2.0.
* `@Repeatable` is missing.
* `@Target(TYPE_USE)` is missing.

This is a lack of fix in #857.

## Affect versions

- 5.5.1.RELEASE
- 5.6.0.RELEASE

## Issue links

- #857

**Comment by yoshikawaa** [comment]
@takahashihrzg Please decide backport to 5.6.x, 5.5.x .

**Comment by yoshikawaa** [comment]
Closed because not discussed about backport.

**Comment by btkatoufm** [comment]
https://github.com/terasolunaorg/terasoluna-gfw/issues/1013#issuecomment-722133467
As a result of the discussion, a backport is required, so we will add a label.
