### ISSUE TITLE
Increase coverage verified with Coveralls

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw#1035]
## Description

Increase coverage verified with Coveralls.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by yoshikawaa** [comment]
https://coveralls.io/builds/35601022
#1037 & #1036 increase coverage to 99.961%.

About the rest, the test has passed [TransactionTokenInterceptor.java#L161](https://coveralls.io/builds/35601022/source?filename=terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptor.java#L161) but is not reflected in the coverage.
This is seems to explain in [jacoco faq](https://www.eclemma.org/jacoco/trunk/doc/faq.html) .

> **Source code lines with exceptions show no coverage. Why?**
> 
> JaCoCo determines code execution with so called probes. Probes are inserted into the control flow at certain positions. Code is considered as executed when a subsequent probe has been executed. In case of exceptions such a sequence of instructions is aborted somewhere in the middle and the corresponding line of source code is not marked as covered.

**Comment by btkatoufm** [comment]
Please backport with a new issue if needed.
