### ISSUE TITLE
Switch from Java EE to Jakarta EE.

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw#1038]
## Description
Migrate Java EE library dependencies to Jakarta EE library. Switch as follows.
|Java EE|Jakarta EE|Remarks|
|-|-|-|
|javax.el:javax.el-api:3.0.1-b06|jakarta.el:jakarta.el-api:4.0.0||
|javax.servlet.jsp:javax.servlet.jsp-api:2.3.3|jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.0.0||
|javax.validation:validation-api:2.0.1.Final|jakarta.validation:jakarta.validation-api:2.0.2|*1|
|javax.servlet:javax.servlet-api:4.0.1|jakarta.servlet:jakarta.servlet-api:4.0.4|*1|

[*1]conforms to spring-boot: 2.4.0

When I migrate `javax.inject` to `jakarta.inject-api`, I get an error because the FQCN of @Inject changes.
Also, [Spring Framework](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-standard-annotations) still only supports javax inject-api.
Therefore, `javax.inject` will not be updated to `jakarta.inject-api`.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.7.0.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by yoshikawaa** [comment]
@btiwahorisu 
> When I migrate javax.inject to jakarta.inject-api, I get an error because the FQCN of @Inject changes.
> Also, Spring Framework still only supports javax inject-api.
> Therefore, javax.inject will not be updated to jakarta.inject-api.

It's a misunderstanding.

* jakarta.inject-api:1.x (for Jakarta EE 8) [supports `javax.*` package](https://github.com/eclipse-ee4j/injection-api/tree/1.0.3/src/main). 
* jakarta.inject-api:2.x (for Jakarta EE 9) [supports `jakarta.*` package](https://github.com/eclipse-ee4j/injection-api/tree/2.0.0/src/main).

`Java EE to Jakarta EE` here means in EE 8. It's too difficult to upgrade to EE 9 at the same time.

HDYT?

**Comment by btiwahorisu** [comment]
You are correct. It was my lack of understanding.
Considering Jakarta EE 8, I think the following is a reasonable version of the library to update.

|Java EE|Jakarta EE|Remarks|
|-|-|-|
|javax.el:javax.el-api:3.0.1-b06|jakarta.el:jakarta.el-api:**3.0.3**||
|javax.servlet.jsp:javax.servlet.jsp-api:2.3.3|jakarta.servlet.jsp:jakarta.servlet.jsp-api:**2.3.6**||
|javax.inject:javax.inject:1|jakarta.inject:jakarta.inject-api:**1.0.3**||
|javax.validation:validation-api:2.0.1.Final|jakarta.validation:jakarta.validation-api:2.0.2|*1|
|javax.servlet:javax.servlet-api:4.0.1|jakarta.servlet:jakarta.servlet-api:4.0.4|*1|

[*1]conforms to spring-boot: 2.4.0
