### ISSUE TITLE
Backport:Update all of Maven plugins managed on terasoluna-gfw

### ISSUE THREAD

**Issue by btootomoyuk** [terasolunaorg/terasoluna-gfw#1055]
## Original Issue
> Links to the original issues.

- Backport https://github.com/terasolunaorg/terasoluna-gfw/issues/1010

**Comment by btkatoufm** [comment]
The correspondence of this ISSUE has been reverted. (https://github.com/terasolunaorg/terasoluna-gfw/pull/1057)
The maintenance version upgrade does not update the plugin version.
