### ISSUE TITLE
Update the version of maven-plugin

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw#1083]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Take the following actions:
- Upgrade the plugin version
- Remove unnecessary plugins.
- Change `com.google.code:maven-license-plugin` to `com.mycila:license-maven-plugin` as described in #600.
- Modify the variable name of the plugin version to be `groupId.artifactId.pugin.version`.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
Since the GPG version of the operating environment is 2.1 or later, the maven-gpg-plugin option is added.
I can't handle it with the command, so I'll change the pom.
https://github.com/terasolunaorg/terasoluna-gfw/pull/1085#discussion_r678738663
