### ISSUE TITLE
Add logback-classic-db

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-gfw#1166]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

DB Appender has been removed from 1.2.8 for logback-core.
Therefore, it is necessary to add `ch.qos.logback.db: logback-classic-db: 1.2.11.1`.
https://logback.qos.ch/news.html

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Add `logback-classic-db` to `terasoluna-gfw-parent/pom.xml` and `terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml`.

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btkawaharahd** [comment]
Logback-classic-db should not be added to `terasoluna-gfw-parent/pom.xml`, but should be added only to `pom.xml` of the required project. Don't use logback db for terasoluna-gfw
Correspond with #1168
