### ISSUE TITLE
Reflect: NumberFormatException occurs in maxDisplayCountBlank when started with Weblogic.

### ISSUE THREAD

**Issue by btkatoufm** [terasolunaorg/terasoluna-gfw#1167]
## Original Issue
> Links to the original issues.

- Reflect terasolunaorg/terasoluna-gfw-functionaltest#924

## Description
> Please write if the description of the original issue is not enough.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

In Weblogic, setting an empty character to a variable that is treated as a number will throw a NumberFormatException during conversion. (In the case of Tomcat, this is interpreted as 0.)

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

To avoid dependence on the AP server, receive data as strings and convert them to numbers yourself.

## Issue links
> Links to related issues.

- #xx

**Comment by yoshikawaa** [comment]
> In Weblogic, setting an empty character to a variable that is treated as a number will throw a NumberFormatException during conversion. (In the case of Tomcat, this is interpreted as 0.)

> To avoid dependence on the AP server, receive data as strings and convert them to numbers yourself.

If you intentionally specify a string value for an int attribute, it is appropriate to throw a NumberFormatException.
You should specify a value of the expected type as an attribute value to avoid dependence on the AP server.
Is "Possible Solution" the result of discussion? By design, I don't feel that it is useful to able to set the space instead of zero.

**Comment by btkatoufm** [comment]
As the specification is defined in https://jakarta.ee/specifications/pages/3.0/jakarta-server-pages-spec-3.0.html#conversions-from-string-values, it is correct to set the value to "0" when an empty character comes in the place where "int or Integer" is expected.

However, the above discussion is only about the JSP definition, and we have decided that it is not healthy to change the terasoluna-gfw specification just because the behavior of some AP servers is strange.

We will close this issue without taking any action.

Thanks.
