### ISSUE TITLE
Update the version of Logback and SLF4J

### ISSUE THREAD

**Issue by btkawaharahd** [terasolunaorg/terasoluna-gfw#1191]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Logback 1.2.11 is Java EE (javax.* namespace), so it should be Jakarta EE (jakarta.* namespace) version

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Update Logback version to 1.4.1 and SLF4J version to 2.0.0

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.8.0.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
Since the version of logback provided by Spring Boot is 1.2.11 at this time, we will tentatively use gfw to update the version.
https://docs.spring.io/spring-boot/docs/3.0.0-M5/reference/htmlsingle/#appendix.dependency-versions

The relevant sections will be removed when the version is updated.
