### ISSUE TITLE
Update the library version

### ISSUE THREAD

**Issue by btkatoufm** [terasolunaorg/terasoluna-gfw#1207]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Uniformly review the version of the library currently in use.
The libraries themselves will be reviewed for areas that are clearly using outdated libraries.
Libraries that do not support JakartaEE10 will be removed.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Change the following

* Update
  * com.github.librepdf:openpdf 1.0.5 -> 1.3.30
  * commons-collections:commons-collections 3.2.2 -> org.apache.commons:commons-collections4 4.4
  * jakarta.el:jakarta.el-api 4.0.0 -> 5.0.1
  * jakarta.servlet.jsp:jakarta.servlet.jsp-api 3.0.0 -> 3.1.0
  * org.apache.commons:commons-compress 1.21 -> 1.22
  * org.apache.poi:poi 4.1.2 -> 5.2.3
  * org.apache.poi:poi-ooxml 4.1.2 -> 5.2.3
  * org.apache.poi:poi-scratchpad 4.1.2 -> 5.2.3
  * org.bouncycastle:bcprov-jdk15on -> org.bouncycastle:bcprov-jdk18on 1.72
  * org.mapstruct:mapstruct 1.5.2.Final -> 1.5.3.Final
  * org.mybatis:mybatis-spring 3.0.0 -> 3.0.1
* New
  * org.glassfish.web:jakarta.servlet.jsp.jstl 3.0.1
* Delete
  * commons-fileupload:commons-fileupload
  * org.apache.taglibs:taglibs-standard-impl
  * org.apache.taglibs:taglibs-standard-jstlel
  * org.apache.taglibs:taglibs-standard-spec

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btootomoyuk** [comment]
Re-opened because of omission of maven-surefire-plugin updates.
