### ISSUE TITLE
[5.7.x]Update the library version

### ISSUE THREAD

**Issue by btkatoufm** [terasolunaorg/terasoluna-gfw#1209]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

Uniformly review the version of the library currently in use.
The version of OSS used by TERASOLUNA will be increased to be compatible with JakartaEE8.
In addition, the libraries themselves will be reviewed for areas that are clearly using outdated libraries.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Change the following

* Update
  * com.github.librepdf:openpdf 1.0.5 -> 1.3.20
  * commons-collections:commons-collections 3.2.2 -> org.apache.commons:commons-collections4 4.4
  * commons-fileupload:commons-fileupload 1.3.3 -> 1.4
  * joda-time:joda-time 2.10.9 -> 2.12.2
  * org.apache.commons:commons-compress 1.21 -> 1.22
  * org.apache.poi:poi 4.1.2 -> 5.2.3
  * org.apache.poi:poi-ooxml 4.1.2 -> 5.2.3
  * org.apache.poi:poi-scratchpad 4.1.2 -> 5.2.3
  * org.bouncycastle:bcprov-jdk15on 1.69 -> org.bouncycastle:bcprov-jdk18on 1.72

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btootomoyuk** [comment]
Reopened due to omission of plugin fixes

**Comment by btootomoyuk** [comment]
Re-opened because of omission of maven-surefire-plugin updates.

**Comment by btootomoyuk** [comment]
Close due to accidental opening of an issue
