### ISSUE TITLE
The test fails due to a problem with the locale setting.

### ISSUE THREAD

**Issue by btkawaharahd** [terasolunaorg/terasoluna-gfw#1269]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

The test fails due to a problem with the locale setting.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Correct regarding locale settings.

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btkatoufm** [comment]
Some unnecessary imports and settings were incorrect.
https://github.com/terasolunaorg/terasoluna-gfw/commit/a1eaab86726b829e51be613aa6ac10af84839e02
