### ISSUE TITLE
Correction of Link

### ISSUE THREAD

**Issue by btkatoufm** [terasolunaorg/terasoluna-gfw#1293]
## Description
> Please write the problem in detail.
> Please write based on facts as much as possible, and post links to references/Javadoc or stack traces.

The link about Stack is pointing to the private repository, so modify it to the public repository.

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

> All modules included in TERASOLUNA Server Framework for Java (5.x) Common Library are listed up in the [development guideline](https://github.com/terasolunaorg/guideline/blob/master/source_en/Overview/FrameworkStack.rst#building-blocks-of-common-library).

Link this to the corresponding version at https://terasolunaorg.github.io/guideline/.

## Affect versions
> Version in which the problem occurs. **Current version if not known.**
> If there is a feature suggestion, please delete it.

- 5.x.x.RELEASE

## Issue links
> Links to related issues.

- #xx

**Comment by btiwahorisu** [comment]
https://github.com/terasolunaorg/terasoluna-gfw/issues/1295
