### ISSUE TITLE
Need a HandlerInterceptor for detects the session time-out ?

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw#21]
Maybe,  DetectsSessionTimeoutHandlerInterceptor(provisional class name)  is needed in many projects.

Provide from a common library is better ?

**Comment by ikeyat** [comment]
Timeout can be detected as seen here when using Spring Security.
http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/en/Security/Authorization.html#accessdeniedhandler
