### ISSUE TITLE
There are some issues in classes for CSRF countermeasures of 1.0.x

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#226]
@making @makits 

There are following issues.

* [SEC-2352](https://jira.spring.io/browse/SEC-2352) (bug in 3.2.0.RC1 ?)
* [SEC-2422](https://jira.spring.io/browse/SEC-2422) (bug in 3.2.0.RC2)
* [SEC-2439](https://jira.spring.io/browse/SEC-2439) (bug in 3.2.0.RC2)
* [SEC-2404](https://jira.spring.io/browse/SEC-2404) (bug in 3.2.0.RC2)

I think applying is better.
How do think ?

If apply above issues, we need adding following classes that added from spring security 3.2 ...
* org.springframework.security.web.util.matcher.RequestMatcher (required) -> package changed
* org.springframework.security.web.access.DelegatingAccessDeniedHandler (optional) -> added

**Comment by making** [comment]
not update at this time to reduce efforts for 1.0.x user to upgrade.
re-consider when the problems related to these reveals.
