### ISSUE TITLE
Investigate Thymeleaf

### ISSUE THREAD

**Issue by making** [terasolunaorg/terasoluna-gfw#248]

**Comment by kazuki43zoo** [comment]
Thymeleaf 2.x has not support JSR 310 Date and Time API's classes. If use these classes, we'll add the `thymeleaf-extras-java8time` as dependency libraries.
I don't know support status at Thymeleaf 3.

**Comment by ikeyat** [comment]
Anyway we never adopt Thymeleaf 2.x becase 3.0 has been released. We should check the status of 3.0.

**Comment by btkatoufm** [comment]
It should have been investigated by macchinetta.
https://macchinetta.github.io/server-guideline-thymeleaf/current/ja/
