### ISSUE TITLE
Update to MyBatis 3.3.0 & MyBatis-Spring 1.2.3

### ISSUE THREAD

**Issue by making** [terasolunaorg/terasoluna-gfw#279]
according to https://github.com/mybatis/mybatis-3/issues/325

**Comment by btshimizukza** [comment]
MyBatis 3.3.0 has been released. But 3.2.9 has not been released.

https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.3.0

**Comment by kazuki43zoo** [comment]
MyBatis-Spring 1.2.3 has been released.

https://github.com/mybatis/spring/releases/tag/mybatis-spring-1.2.3

**Comment by kazuki43zoo** [comment]
Label change to `task` from `bug` because mybatis/mybatis-3#325 is not bug.
