### ISSUE TITLE
Add migration procedure of <sec:headers> in wiki page

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw#289]
## Description
Currently, migration procedure of the `<sec:headers>` is not exist in the Migration Guide for 5.0.0.

## Possible Solutions
I think should be add a procedure of the `<sec:headers>` and notes.

## Affects Version/s
* 5.0.0.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/wiki/Migration-Guide-5.0.0
* https://github.com/terasolunaorg/terasoluna-gfw/wiki/Migration-Guide-5.0.0_ja

**Comment by ikeyat** [comment]
These wiki is not included in terasoluna-gfw repository.
Skip this issue when make tags for RC and RELEASE.

**Comment by ikeyat** [comment]
I would not like to manage issues for wiki here.
I moved this issue to internal management. So I close this.
