### ISSUE TITLE
f:query throws ConverterNotFoundException when the target object contains nested field

### ISSUE THREAD

**Issue by making** [terasolunaorg/terasoluna-gfw#297]
## Description

`f:query` is sometime used with an object which has nested field.
In this case, `f:query` throws `ConverterNotFoundException` even if the fields is not intended to use.

For example,

``` java
Foo foo = new Foo();
Bar bar = new Bar();
bar.setValue("foo");
foo.setBar(bar);
foo.setName("aa");
String query = Functions.query(foo); // ConverterNotFoundException occurs!!
```

``` java
class Foo {
    private String name;
    private Bar bar;
    // ...
}

class Bar {
    private String value;
    // ...
}
```
## Possible Solutions
Implement the following two:

~~1. (Default) Ignore `ConverterNotFoundException` -> PR #306~~
1. Support nested fields. (resolving by this issue)
2. Add an arity taking `ConversionService` in order to provide how to format the nested field. 　This means adding new `f:query(Object, ConversionService)`. This resolves #125 .

## Affects Version/s
* 5.0.0.RELEASE
* 1.0.2.RELEASE

## Fix Version/s
- [x] 5.0.1.RELEASE
- [x] 5.1.0.RELEASE

## Issue Links

* #125
* terasolunaorg/guideline#305

**Comment by kazato** [comment]
:+1:

The proposed solution looks good to me.
Thank you, @making !

**Comment by making** [comment]
My mind has been changed.

`ConverterNotFoundException` should not be ignored because nested fields should be transferred to next screen.
So nested fields should be printed.

The following is pseudo code :

### Pattern0

`toQueryMap` is put in the `query` method.

```
class SearchUserForm {
  String name;
  Integer age;
}

form = new SearchUserForm("yamada", 20);


toQueryMap(form, "" /* prefix */)
↓
{"name":"yamada", "age":"20"}

query(form)
↓ concatenate
name=yamada&age=20
```

### Pattern1

```
class SearchUserForm {
  SearchUserCriteriaForm criteria;
  boolean rememberCriteria;
}

class SearchUserCriteriaForm {
  String name;
  Integer age;
}


form = new SearchUserForm(new SearchUserCriteriaForm("yamada", 20), true);


toQueryMap(form, "")

↓
↓
↓	toQueryMap(form.criteria, "criteria")
↓	↓
↓	{"criteria.name":"yamada", "criteria.age":"20"}
↓
↓ merge map
{"rememberCriteria":"true", "criteria.name":"yamada", "criteria.age":"20"} 


query(form)
↓
rememberCriteria=true&criteria.name=yamada&criteria.age=20
```

### Pattern2

```
class BatchUpdateUserForm {
  List<UpdateUserCriteriaForm criteria;
  LogicalOperator operator;
}

enum LogicalOperator {
  AND, OR
}

class UpdateUserForm {
  String name;
  Integer age;
}


form = new BatchUpdateUserForm([new UpdateUserForm("yamada", 20), new UpdateUserForm("tanaka", 50)], LogicalOperator.AND);


toQueryMap(form, "")
↓
↓
↓	toQueryMap(form.criteria[0], "criteria[0]")
↓	↓
↓	{"criteria[0].name":"yamada", "criteria[0].age":"20"}
↓
↓	toQueryMap(form.criteria[1], "criteria[1]")
↓	↓
↓	{"criteria[1].name":"tanaka", "criteria[1].name":"50"}
↓
{"criteria[0].name":"yamada", "criteria[0].age":"20", "criteria[1].name":"tanaka", "criteria[1].name":"50", "operator":"AND"}


query(form)
↓
criteria[0].name=yamada&criteria[0].age=20&criteria[1].name=tanaka&criteria[1].name=50&operator=AND
```

### Pattern3

```
class SearchAndBatchUpdateUserForm {
  SearchUserCriteriaForm criteria;
  List<User> users;
}

class SearchUserCriteriaForm {
  String name;
  Integer age;
}

class User {
  String name;
  Integer age;
}


form = new SearchAndBatchUpdateUserForm(new SearchUserCriteriaForm("suzuki", 30), [new User("yamada", 20), new User("tanaka", 50)]);


toQueryMap(form, "")
	
	toQueryMap(form.criteria, "criteria")
	↓
	{"criteria.name":"suzuki", "criteria.age":"30"}

	toQueryMap(form.users[0], "users[0]")
	↓
	{"users[0].name":"yamada", "users[0].age":"20"}

	toQueryMap(form.users[1], "users[1]")
	↓
	{"users[1].name":"tanaka", "users[1].age":"50"}

query(form)
↓
criteria.name=suzuki&criteria.age=30&users[0].name=yamada&users[0].age=20&users[1].name=tanaka&users[1].age=50
```

**Comment by making** [comment]
I found similar functionality is provided by Spring Integration.
https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/transformer/ObjectToMapTransformer.java

**Comment by making** [comment]
@btshimizukza @kazuki43zoo 

I've commit a prototype to support nested field in `f:query`.
https://github.com/terasolunaorg/terasoluna-gfw/commit/d5b59bd8be71099e4cf5820498b7c59c0862d69d

Please review the strategy.

**Comment by kazuki43zoo** [comment]
Hi @making, i have commented to the internal e-mail.
Please confirm comments.

**Comment by btshimizukza** [comment]
Reopen because problem was found.

**Comment by making** [comment]
Remove comment https://github.com/terasolunaorg/terasoluna-gfw/blob/release/5.0.1.RC2/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java#L216-L235

**Comment by btshimizukza** [comment]
If element value of `Iterable` , Array and `Map` is `null`, a reset parameter that start with `"_"` does not show in query string. Therefore default value has restored at pagination request.

We should be show a reset parameter, if element value is `null`.

**Comment by btshimizukza** [comment]
Improve API document.
