### ISSUE TITLE
Update the tomcat version of tomcat7-maven-plugin to latest version

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#318]
## Description
Currently, tomcat version of tomcat7-maven-plugin is 7.0.59.
But 7.0.67 has been released.

## Possible Solutions
Update to same version with Spring IO Platform.

## Affects Version/s
* 5.0.1.RELEASE

## Fix Version/s
-  5.1.0.RELEASE replace to  cargo-maven2-plugin (will be resolved via #451)
- [x] 5.0.2.RELEASE update the version of tomcat7-maven-plugin

## Issue Links
None

**Comment by making** [comment]
How about Tomcat8?

**Comment by kazuki43zoo** [comment]
I want to consider replacing to [cargo-maven2-plugin](https://codehaus-cargo.github.io/cargo/Maven2+plugin.html) from tomcat7-maven-plugin.
cargo-maven2-plugin is support many application servers and versions.

**Comment by kazuki43zoo** [comment]
I tried cargo-maven2-plugin. please see f2286cd176d13178fab05585defed9a7f1c1036a .

**[Multi blank project]**
```console
mvn clean package -DskipTests=true
mvn -f projectName-web/pom.xml cargo:run
```
\* `-DskipTests=true` is required for prevent a selenium test execution. (temporary workaround)

**[Single blank project]**
```console
mvn clean package
mvn cargo:run
```

**[Note]**
In this commit, Tomcat 8 is default.
If Tomcat 7 use, please switch to profile for Tomcat 7 as follow.

```console
mvn cargo:run -P tomcat7
```

**Comment by ikeyat** [comment]
Please replace tomcat7-plugin to cargo-maven2-plugin for 5.1.0.RELEASE only.
I found tomcat7-plugin is not used by our blank-project, tourreservation and functionaltests.

**Comment by btshimizukza** [comment]
`cargo-maven2-plugin` 1.4.17 has been released.

**Comment by kazuki43zoo** [comment]
@ikeyat 
I created new issue(#451) for supporting carog-maven2-plugin.
