### ISSUE TITLE
Upgrade to Spring IO Platform 2.0

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw#362]
## Description
Upgrade to Spring IO Platform 2.0 for 5.1.0 release.
At the first, we investigate main changes and impacts in framework stack libraries.

## Possible Solutions
- [x] Modify version as follows.

e.g)
```xml
<io.spring.platform.version>2.0.1.RELEASE</io.spring.platform.version>
```

 > **Note:** 
 >   Use latest maintenance version at the time of release

- [x] Apply 2.0.0.RC1
- [x] Apply SPR-11912 (https://github.com/terasolunaorg/terasoluna-gfw/issues/362#issuecomment-128737415)
- [x] Apply SPR-13277 (https://github.com/terasolunaorg/terasoluna-gfw/issues/362#issuecomment-128747667)
- [x] Apply 2.0.0.RELEASE (#408)
- [x] Apply 2.0.1.RELEASE ? (refer to #444)

## Affects Version/s
\-

## Fix Version/s
- [x] 5.1.0

## Issue Links
* https://github.com/spring-io/platform/milestones/2.0.0.M1
* https://github.com/spring-io/platform/milestones/2.0.0.RC1
* https://github.com/spring-io/platform/milestones/2.0.0.RELEASE

**Comment by btshimizukza** [comment]
Changes at the time of 2015-08-07

**[Framework Stack Libraries]**

| Library Name | Spring IO Platform 1.1.3 (gfw-5.0.1)| Spring IO Platform 2.0.0.BUILD-SNAPSHOT | Remarks |
|:---:|:---:|:---:|---|
| Spring Framework | 4.1.7.RELEASE | 4.2.0.RELEASE |  |
| Spring Security | 3.2.7.RELEASE | 4.0.2.RELEASE |  |
| Spring Data Commons | 1.9.3.RELEASE | 1.11.0.RC1 |  |
| Spring Data JPA | 1.7.3.RELEASE | 1.9.0.RC1 |  |
| Spring Boot | 1.2.5.RELEASE | 1.3.0.BUILD-SNAPSHOT | dependency management only |
| Hibernate Validator | 5.1.3.Final | 5.2.1.Final |  |
| Jackson | 2.4.6 | 2.5.4 |  |
| Joda Time | 2.5 | 2.8.1 |  |
| Commons DBCP 2 | 2.0.1 | 2.1 |  |
| Commons Pool 2 | 2.2 | 2.4.2 |  |

**[Use in blank project as `provided` or `test` scope]**

| Library Name | Spring IO Platform 1.1.3 (gfw-5.0.1)| Spring IO Platform 2.0.0.BUILD-SNAPSHOT | Remarks |
|:---:|:---:|:---:|---|
| Tomcat API | 7.0.59 | 8.0.23 | scope is `provided` |
| JUnit | 4.11 | 4.12 | scope is `test` |

**[Note]**

Following artifacts has been managed from Spring IO Platform 2.0.

* spring-security-data
* spring-security-messaging
* spring-security-test
* hibernate-validator-annotation-processor

**Comment by kazuki43zoo** [comment]
In terasoluna-gfw-web, `ResponseUtilsTest#testSetPreventionCachingHeaders` is failed.
Failed reason is improvement of spring-test module. For details, refer to [SPR-11912](https://jira.spring.io/browse/SPR-11912) .

Change a assertion as follows:
[Before]
```java
assertThat(response.getHeader("Expires"), is("1"));
```

[After]
```java
assertThat(response.getHeader("Expires"), is("Thu, 01 Jan 1970 00:00:00 GMT"));
```

**Comment by kazuki43zoo** [comment]
In terasoluna-gfw-jodatime, `JdbcAdjustedJodaTimeDateFactoryTest` is used a deprecated API (`@TransactionConfiguration`). For details, refer to [SPR-13277](https://jira.spring.io/browse/SPR-13277) .

Change to use `@Rollback` instead of `@TransactionConfiguration(defaultRollback = true)` as follows:

```java
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath:test-context.xml" })
@Transactional
@Rollback // ### <- Modify here
public class JdbcAdjustedJodaTimeDateFactoryTest {
    // ...
}
```

**Comment by making** [comment]
Spring IO Platform 2.0.0.RC1 has been released.

Start regression testing with this at first @iwanagah 
http://spring.io/blog/2015/10/29/spring-io-platform-2-0-0-rc1

**Comment by btokadanob** [comment]
## Spring IO PF 2.0.0.RELEASE 対応 11/20 作戦会議##

* 作業の目的
 1. TERASOLUNA GFW 5.0.1版で利用しているspringおよびその他OSSと最新版spring io pfの差分を確認、調査、及び修正


* ゴール (何をどこまでやれば目的達成されるか)
 1. リグレッションが通る事を確認する。→　基本すべて<br>http://10.68.254.64:8888/terasolunaorg/development-policy/blob/master/ReleasePolicy.rst
 1. リリースノート、ドキュメントを確認し、新機能の追加などあればテストアプリなどへの導入、ガイドライン加筆など対処する
 1. リリースノート、ドキュメントを確認し、非推奨機能が存在している場合テストアプリなど修正、ガイドライン加筆など対処する。
 1. 加えて、全APサーバでALLグリーン
 1. 以前の対応の暫定対処が妥当であるか確認する。<br>
http://10.68.254.64:8888/terasolunaorg/spring-functionaltest/issues/212
    > * issues#337 [http://10.68.254.64:8888/terasolunaorg/spring-functionaltest/issues/337]
    > * issues#231 [http://10.68.254.64:8888/terasolunaorg/spring-functionaltest/issues/231]
    > * issues#236
    [http://10.68.254.64:8888/terasolunaorg/spring-functionaltest/issues/236]
    > * issues#248 [http://10.68.254.64:8888/terasolunaorg/spring-functionaltest/issues/248]
    > * issues#250 [http://10.68.254.64:8888/terasolunaorg/spring-functionaltest/issues/250]
    > * issues#315 [http://10.68.254.64:8888/terasolunaorg/spring-functionaltest/issues/315]

* 差分確認手段
 1. バージョン差分については各種OSSのリリースノートを確認する。spring jiraとか
 1. dependからひもづいたて落ちてきたPatch版やRC版はUpdateを検討する。


* 対象範囲
 1. ガイドラインのスタックライブラリに上がっているものが対象で、Terasoluaが独自にバージョンを指定しているものも確認する


* 担当割り振り
 1. AP動かす okada → 11/24～11/27
 1. RC版の存在確認、どの資材を確認するかを一覧化する : okada  11/24～12/1 AM
 1. リリースノートチェック：hoge
 1. 修正系:hoge

* 成果物
 1. バージョンアップに依る、修正ポイントと影響箇所をまとめたもの↓
 1. マイグレーションガイド[https://github.com/terasolunaorg/terasoluna-gfw/wiki]


* スケジュール
 1. マイグレーション覗いて12末まで！

* 稼働
 1. 岡田は0.6稼働 週2は倉元さんとFrSS作業に入る予定です
 1. このタスクは年末まで、という話。

**Comment by btshimizukza** [comment]
We need to watch release timing of 2.0.1 for #444.

**Comment by kazuki43zoo** [comment]
2.0.1.RELEASE has been released.
http://spring.io/blog/2015/12/18/spring-io-platform-2-0-1-release

**Comment by kazuki43zoo** [comment]
I've updated library versions of framework stack.

**Comment by making** [comment]
@ikeyat please check http://spring.io/blog/2016/02/01/spring-io-platform-2-0-2-release

**Comment by ikeyat** [comment]
@making 
We decided not to update.
Actually the release seems not to be directly related to our stack.
Anyway our tests have started at the time so that it's difficult to replace its version at the time.
