### ISSUE TITLE
Support fallback language at SimpleI18nCodeList

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#363]
## Description

In current implementation of `SimpleI18nCodeList`, we needs to define same definition per locale string pattern (e.g. `ja`, `ja_JP`) as follows:

``` xml
    <util:map id="existenceMapJa">
        <entry key="0" value="無" />
        <entry key="1" value="有" />
    </util:map>

    <bean id="CL_EXISTENCE" class="org.terasoluna.gfw.common.codelist.i18n.SimpleI18nCodeList">
        <property name="rows">
            <util:map>
                <entry key="en">
                    <util:map>
                        <entry key="0" value="No" />
                        <entry key="1" value="Yes" />
                    </util:map>
                </entry>
                <entry key="ja" value-ref="existenceMapJa" />
                <entry key="ja_JP" value-ref="existenceMapJa" />
            </util:map>
        </property>
    </bean>
```

It's not intuitive and simple.
## Possible Solutions

I want to define as follows:

``` xml
    <bean id="CL_EXISTENCE" class="org.terasoluna.gfw.common.codelist.i18n.SimpleI18nCodeList">
        <property name="rows">
            <util:map>
                <entry key="en">
                    <util:map>
                        <entry key="0" value="No" />
                        <entry key="1" value="Yes" />
                    </util:map>
                </entry>
                <entry key="ja">
                    <util:map>
                        <entry key="0" value="無" />
                        <entry key="1" value="有" />
                    </util:map>
                </entry>
            </util:map>
        </property>
    </bean>
```

For example:
If locale string is `ja_JP`, find `Map` by following priority.
- `Map` that correspond to `ja_JP`
- `Map` that correspond to `ja` (only language without country) *1
- `Map` that correspond to fallback locale(default is `Locale.getDefault()`) *1
- Empty `Map`

*1 Adding as new option

How do think ?
## Affects Version/s
- 5.0.0.RELEASE - 5.0.1.RELEASE
- 1.0.0.RELEASE - 1.0.3.RELEASE
## Fix Version/s
- [x] 5.5.1

## Issue Links

Nothing

**Comment by yoshikawaa** [comment]
@btkobayashirun 
I think default fallback locale ( `Locale.getDefault()` ) should be fallbacked to it's language locale.
Because result of `Locale.getDefault()` is ex. `en_US`, `ja_JP`, however we generally want to define language locales into `SimpleI18nCodeList` to effectively use fallback to the language locale.

Changes ex...
```java
protected Locale fallbackTo = null;

public void afterPropertiesSet() {
  Assert.notNull(codeListTable, "codeListTable is not initialized!");
  if (fallbackTo == null) {
    fallbackTo = resolveLocale(Locale.getDefault());
    Assert.notNull(fallbackTo, ...);
  } else {
    Assert.isTrue(codeListTable.containsRow(fallbackTo), ...);
  }
}
```
