### ISSUE TITLE
Support @AliasFor in @TransactionTokenCheck

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#364]
## Description
At the Spring 4.2, annotation can be have a alias attribute.

## Possible Solutions
We consider adding a alias attribute as follows.

```java
public @interface TransactionTokenCheck {

    @AliasFor("namespace") // ### Modify
    String value() default "";

    // ### Add a new attribute
    @AliasFor("value")
    String namespace() default "";

    TransactionTokenType type() default TransactionTokenType.IN;
}
```

`@TransactionTokenCheck(namespace = "cancel", type = TransactionTokenType.IN)` is equivalent to
`@TransactionTokenCheck(value = "cancel", type = TransactionTokenType.IN)`.

## Affects Version/s
\- 

## Fix Version/s
- [x] 5.1.0

## Issue Links
Nothing

**Comment by btshimizukza** [comment]
@ikeyat @btjinbotm 

Please reflect to the [guideline](http://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/DoubleSubmitProtection.html).
