### ISSUE TITLE
Support Coveralls

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#380]
## Description

Support [Coveralls](https://coveralls.zendesk.com) (using [coveralls-maven-plugin](https://github.com/trautonen/coveralls-maven-plugin)) via Travis-CI  for reporting code coverage.

## Possible Solutions
see [here](https://github.com/trautonen/coveralls-maven-plugin).

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2
- [x] 1.0.4
- [x] exclude spring security sources on 1.0.x(move to #463)

## Issue Links
N/A

**Comment by kazuki43zoo** [comment]
I tried Coveralls using forked repository. For details, refer to following pages:

* Coveralls refer to [here](https://coveralls.io/builds/3875536).
* Changes refer to [here](https://github.com/kazuki43zoo/terasoluna-gfw/commit/6b02f2f75aea9d82a5ae87131b6c9a032a3c58af).

**Comment by ikeyat** [comment]
@btshimizukza 
That sounds great! Could you contribute to original repository?

**Comment by making** [comment]
Add the badge on README
