### ISSUE TITLE
Add CodePoint-based validaton

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#390]
## Description
In general, codepoint-based validation is required for user's input values in web application.

## Possible Solutions
Add ``CodePoints`` class that manage and define codepoints. It also have functions to validate which targets include specified codepoints or not.
In addition, a validator based on BeanValidation will be added that supports ``CharSequence``.

## Affects Version/s
* N/A

## Fix Version/s
- [x] 5.1.0
- [x] 5.1.0 (remove `<version> tag`)

**Comment by ikeyat** [comment]
@making Please fill descriptions (overview) on this issue.

**Comment by ikeyat** [comment]
I

**Comment by kazuki43zoo** [comment]
Remove unnecessary `<version>` tag on `pom.xml`.
