### ISSUE TITLE
Move license header files to the top level

### ISSUE THREAD

**Issue by making** [terasolunaorg/terasoluna-gfw#424]
## Description
Currently, license header files are located at each project.
It's inconvenient to maintain.

## Possible Solutions

Move files `header` directory on the top of this project.
Then, refer this directory relatively from each project.

## Affects Version/s
* 1.0.x
* 5.0.x

## Fix Version/s
- [x] 5.1.0.RELEASE
- [x] 5.0.2.RELEASE
- [x] 1.0.4.RELEASE

**Comment by btshimizukza** [comment]
Thanks for merging.

I want to backport to 5.0.x and 1.0.x for keeping maintainability.
Is OK ?

**Comment by ikeyat** [comment]
@btshimizukza 
Of course yes. It does not include external changes so that it might impacts nothing to users.
