### ISSUE TITLE
Deploy to Maven Central repository

### ISSUE THREAD

**Issue by making** [terasolunaorg/terasoluna-gfw#425]
## Description
To reduce the maintenance cost for our repo server and increase SLA, we will migrate our artifacts from http://repo.terasoluna.org to Maven Central.

## Possible Solutions
See the comment https://github.com/terasolunaorg/terasoluna-gfw/issues/425#issuecomment-206135505

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0.RELEASE
- TBD 5.1.1.RELEASE

**Comment by btshimizukza** [comment]
:+1:

**Comment by ikeyat** [comment]
Through  [Maven Central page](http://search.maven.org/) we can access the guide how to register.
http://central.sonatype.org/pages/ossrh-guide.html#deployment

It says there are some steps and some requirements for packaging.
* Application by JIRA    
* Requirements for the packaging  
    http://central.sonatype.org/pages/requirements.html
    * javadoc and sources
    * pom.xml
    * sign files
    * etc...
* Maven configuration to deploy  
    http://central.sonatype.org/pages/apache-maven.html

http://tagomoris.hatenablog.com/entry/20141028/1414485679
This is a personal and Japanese blog, but it will help us to know the process of this task.

We would like to begin to know the impact to follow the requirements. After that  we try to deploy SNAPSHOT with stable master branch.

**Comment by ikeyat** [comment]
I created an issue for ``org.terasoluna``.
https://issues.sonatype.org/browse/OSSRH-21650

**Comment by ikeyat** [comment]
@btmiyashitasts 
Please modify our ``pom.xml`` to follow the requirements.
http://central.sonatype.org/pages/requirements.html

**Comment by ikeyat** [comment]
@btyoshikawaa 
Please continue this activity.
* In my understanding, some plugins shown the site (staging, release, sign) should be added for some pom.xml those will be deployed.
* Keep to deploy domestic nexus server.
* Test with snapshot version. Then with 5.2.0.RC2
* Archetypes (blank projects) should be deployed as same. (Please create issues and do after this issue)
* 5.1.1 is targeted as best-effort (not mandatory).

**Comment by making** [comment]
FYI

Check how to deploy Maven Central with Travis CI

https://github.com/making/travis-ci-maven-deploy-skelton
sample
https://github.com/making/marked4j

**Comment by ikeyat** [comment]
@making
Thanks!

**Comment by ikeyat** [comment]
Actual deployment was postponed as seen #620 because of some technical problems.
