### ISSUE TITLE
update copyright 2015->2016

### ISSUE THREAD

**Issue by iwanagah** [terasolunaorg/terasoluna-gfw#438]
## Description
Update copyright 2015->2016 because the next release is going to be next year.

## Possible Solutions
update copyright 2015->2016

## Affects Version/s
* 5.0.x
* 1.0.x

## Fix Version/s
- [x] 5.1.0.RELEASE (later)
- [x] 5.0.2.RELEASE
- [x] 1.0.4.RELEASE

## Issue Links
https://github.com/terasolunaorg/terasoluna-gfw/issues/424

**Comment by ikeyat** [comment]
@btfurukawatkr 
Please begin with existing version line 1.0.x and 5.0.x.
