### ISSUE TITLE
Support cargo-maven2-plugin

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#451]
## Description
Add plugin management for cargo-maven2-plugin.

**Note:**
Separated from #318 .

## Possible Solutions
For details, refer to https://github.com/terasolunaorg/terasoluna-gfw/issues/318#issuecomment-143416131.

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.1.0 (Replace instead of tomcat7-maven-plugin)
- [x] 5.0.2
- [x] 1.0.4

## Issue Links
* #318

**Comment by kazuki43zoo** [comment]
I want to backport to 5.0.x and 1.0.x for improving maintainability on other project (e.g. terasoluna-gfw-functionaltest, terasoluna-tourreservation, etc ...).
What do you think ?

**Comment by ikeyat** [comment]
In my opinion, we need to take care for existing users.
My idea is that add cargo-maven2-plugin as ``<dependencyManagement>`` for all versions but keep tomcat7-maven-plugin on 5.0.x and 1.0.x.

**Comment by kazuki43zoo** [comment]
@ikeyat i agree your opinion!
