### ISSUE TITLE
Keep back compability in 5.0.x from updating MyBatis3.3

### ISSUE THREAD

**Issue by btfurukawatkr** [terasolunaorg/terasoluna-gfw#480]
## Description
We update MyBatis3.3 on 5.0.x.
https://github.com/terasolunaorg/guideline/issues/1384
For back compatibility, it is necessary to configure to use CGLIB explicitly instead of JAVASSIST (default).

## Possible Solutions
See https://github.com/terasolunaorg/guideline/pull/1388/files to know how to use CGLIB on MyBatis3.

## Affects Version/s
- 5.0.1

## Fix Version/s
- [ ] 5.0.2

## Issue Links
https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/220

**Comment by ikeyat** [comment]
The reason why closed is #481
