### ISSUE TITLE
NPE when undeploying app with JPA and StdDateFormat

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#491]
## Description

When undeploying application that is using both JPA and Jackson libraries, a following exception is thrown.

```
Destroy method on bean with name 'com.fasterxml.jackson.databind.util.StdDateFormat#ec5c69d' threw 
java.lang.NullPointerException: null
    at java.text.DateFormat.hashCode(DateFormat.java:739) ~[na:1.8.0_45]
    at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106) ~[na:1.8.0_45]
    at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097) ~[na:1.8.0_45]
    at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessBeforeDestruction(PersistenceAnnotationBeanPostProcessor.java:374) 
...
```

The cause seems to be a bug of `StdDateFormat` in Jackson.
https://github.com/FasterXML/jackson-databind/issues/1130

In TERASOLUNA Framework, when implementing REST service we usually creat `StdDateFormat` as a bean as seen here.
https://terasolunaorg.github.io/guideline/5.0.1.RELEASE/ja/ArchitectureInDetail/REST.html#restful-web-servicespring-mvc
## Possible Solutions

Import improved Jackson.
## Affects Version/s
- 5.1.0
- 5.0.2
- 1.0.4
## Fix Version/s
- [x] 5.3.0

**Comment by kazuki43zoo** [comment]
This issue will fix at Jackson 2.7.2.

**Comment by ikeyat** [comment]
The version of jackson cannot be imported to 5.2.x line.
This exception is not so critical and the condition is rare so we postpone to 5.3.0+ release.

**Comment by btyoshikawaa** [comment]
@sasakitsy
Spring IO Platform Athenes applyed. Jackson version is 2.8.4.

**Comment by kazuki43zoo** [comment]
@sasakitsy Please assign a verifier for this fix.

**Comment by kazuki43zoo** [comment]
@sasakitsy 

Please assign a verifier for this fix.

**Comment by bttakehirah** [comment]
Confirmed the error, and the problem was solved.
