### ISSUE TITLE
Update  README.md for 5.1.0+

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-gfw#507]
## Description
We need to update "Projects of Common Library" and "Getting Started" in `README.md`

* Adding new projects (terasoluna-gfw-codepoints, terasoluna-gfw-string, terasoluna-gfw-validator, terasoluna-gfw-web-jsp)

* Update "functionalities" in terasoluna-gfw-web and terasoluna-gfw-security-web

## Affects Version/s
* 5.1.1
* 5.1.0

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1
- ~~[ ] 5.1.0 ?~~ (see https://github.com/terasolunaorg/terasoluna-gfw/issues/507#issuecomment-190012981)

## Issue Links
N/A

**Comment by ikeyat** [comment]
@btshimizukza 
I would like to omit those description from README because those are redundant information.
For 5.1.0, it had been released so that we had better change nothing even if some description is insufficient.

**Comment by btshimizukza** [comment]
@ikeyat 

OK. I agree your opinion.
I suggest that it replace to [the link of guideline](https://github.com/terasolunaorg/guideline/blob/master/source_en/Overview/FrameworkStack.rst#building-blocks-of-common-library).
