### ISSUE TITLE
Separate pom.xml dependencies for app and common lib

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#508]
## Description
Now we define TERASOLUNA Stack libraries in pom.xml of each common libraries.
But for maintainability, it should be separated the dependencies that are just stacks (not used by common libraries directly) or used by common libraries. 

In other words, All dependencies in common libraries (e.g. ``terasoluna-gfw-common``)  should be used by common libraries directly. Other dependencies should be defined other separated pom.xml such as ``terasoluna-gfw-recommended``
The concept is similar to ``xxx-starter`` in Spring Boot.

## Possible Solutions
* Identify all dependencies which they are used or not used by common libraries.
* Define new pom.xml files lineup for each purpose like common, web, jsp, security, rest, jpa, mybatis3, etc...

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0

**Comment by bttanakagn** [comment]
Dependencies projects don't need artifacts with test scope. I will exclude them.

**Comment by ikeyat** [comment]
@bttanakagn 
Please take care for https://github.com/terasolunaorg/terasoluna-gfw/issues/538#issuecomment-223201762 because it is very close to this task.

**Comment by ikeyat** [comment]
Failed when maven deploying via ``mvn-build-all.sh`` because ``terasoluna-gfw-parent`` has no ``<repository>``.
Please fix. @btyoshikawaa

**Comment by ikeyat** [comment]
- [ ] Need tp refactor  https://github.com/terasolunaorg/terasoluna-gfw/issues/508#issuecomment-229638734
