### ISSUE TITLE
Update Selenium Firefox Driver for 2.52.0+

### ISSUE THREAD

**Issue by btsatoukzn** [terasolunaorg/terasoluna-gfw#511]
## Description

When functionaltest(5.2.0-snapshot) run, An error has occurred in firefox version 44.0.2.
At that time Selenium Firefox Driver version was 2.46.0.

The version of the Selenium Firefox Driver was updated to 2.52.0, the test was successful.

Maven Repository - Selenium Firefox Driver
http://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-firefox-driver
## Possible Solutions

Update version of Selenium Firefox Driver from 2.46.0 to 2.52.0+.
## Affects Version/s
- 1.0.4
- 5.0.2
- 5.1.0
## Fix Version/s
- [ ] 5.2.0
- [ ] 5.1.1
- [ ] 5.0.3
- [ ] 1.0.5

**Comment by btshimizukza** [comment]
@btsatoukzn 

English please !

**Comment by ikeyat** [comment]
This version up impacts many exisisting test scenearios regarding screen scrolling.
For the temporal solution, we postpone this update until they can be fixed.

**Comment by ikeyat** [comment]
@btmiyashitasts 
Please revert #512 for the master branch.

**Comment by ikeyat** [comment]
The impact to update ver is large so that we are pending this task.

**Comment by btkatoufm** [comment]
It is outside the scope of the common library.
