### ISSUE TITLE
Spelling Mistake in README.md

### ISSUE THREAD

**Issue by btundes** [terasolunaorg/terasoluna-gfw#514]
## Description
It seems there is a spelling mistake in `README.md` file
Details are-
	Section : ```Projects of Common Library```
	SR NO : 1
	Name of the column having spell mistake : Functionalities
	Misspelled text : * Query <b> excaping </b>utilities for SQL, JPQL

## Possible Solutions
The text can be modified as below-
###### Before correction
Query excaping utilities for SQL, JPQL

###### After correction
Query escaping utilities for SQL, JPQL

## Affects Version/s
- 5.1.0
- 5.0.3
- 1.0.4

## Fix Version/s
- ~~[ ] 5.2.0~~ fixed at #507
- ~~[ ] 5.1.1~~ fixed at #507
- [x]  5.0.3
- [x]  1.0.5

## Issue Links
#507

**Comment by ikeyat** [comment]
assinged to  btkadotahr
