### ISSUE TITLE
[Wiki] Description for URI(Query String) Encoding on JBoss is not correct

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#518]
## Description

Probably, [description](https://github.com/terasolunaorg/terasoluna-gfw/wiki/JBoss_ja#uri%E3%82%A8%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%AE%E8%A8%AD%E5%AE%9A) is not correct.

In wiki page, it has introduced as follow.

```xml
<system-properties>
    <property name="org.apache.catalina.connector.URI_ENCODING" value="UTF-8"/>
    <property name="org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING" value="true"/>
</system-properties>
```

However, this description is not correct.
To be exact ...,

If encoding is fixed, we can use the `org.apache.catalina.connector.URI_ENCODING` property.

```xml
<system-properties>
    <property name="org.apache.catalina.connector.URI_ENCODING" value="UTF-8"/>
</system-properties>
```

or

If encoding is fixed or dynamic, we can use the `org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING` property. (set a encoding using the `ServletRequest#setCharacterEncoding(String)`)

```xml
<system-properties>
    <property name="org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING" value="true"/>
</system-properties>
```

## Possible Solutions
Modify description on Wiki page.

## Affects Version/s
\-

## Fix Version/s
\-

## Issue Links
N/A

**Comment by ikeyat** [comment]
@kazuki43zoo 
I wonder why it is wrong.
To encode both query in URI and request body, we may need both configs. Then the description looks correct.

**Comment by kazuki43zoo** [comment]
@ikeyat 
Sorry, current description **is not wrong**.
But, i created a issue because there are case that can resolved by specifying either the property. 

Modifying for this issue is not mandatory.

**Comment by ikeyat** [comment]
@kazuki43zoo 
In my understanding, ``org.apache.catalina.connector.URI_ENCODING`` is for queries in URI and ``org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING`` is for queries in request body.
If an application accepts both type of queries, both configs are required.
If it accepts either type of query, both are not required. 
Is your advice to describe precisely that these configs should be used case by case, right?

**Comment by kazuki43zoo** [comment]
@ikeyat 
My understanding are follows:

## For queries in request body
If will specify an encoding, application should be set an encoding using `ServletRequest#setCharacterEncoding(String)`.

```java
request.setCharacterEncoding("UTF-8");
```
**Result :**
"UTF-8" is applied. If does not call the `ServletRequest#setCharacterEncoding(String)`, "ISO-8859-1" is applied.

## For queries in URI
If will specify an encoding, there are 2 options.

---
(1)
Specify a **fix encoding** using `org.apache.catalina.connector.URI_ENCODING`.

```xml
<system-properties>
    <property name="org.apache.catalina.connector.URI_ENCODING" value="UTF-8"/>
</system-properties>
```
**Result :**
"UTF-8" is applied.

---
(2)
Specify a **same encoding with request body**(= `ServletRequest#setCharacterEncoding(String)`) using `org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING=true`. If `false` (default value) is specified, "ISO-8859-1"(default encoding) is applied.

```java
request.setCharacterEncoding("Windows-31J");
```
```xml
<system-properties>
    <property name="org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING" value="true"/>
</system-properties>
```
**Result :**
"Windows-31J" is applied. If does not call the `ServletRequest#setCharacterEncoding(String)`, "ISO-8859-1" is applied.

And if will specify a default encoding(fallback encoding) for queries in URI, use both settings.

```java
request.setCharacterEncoding("UTF-8");
```
```xml
<system-properties>
    <property name="org.apache.catalina.connector.URI_ENCODING" value="UTF-8"/>
    <property name="org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING" value="true"/>
</system-properties>
```
**Result:** 
"UTF-8" is applied. If does not call the `ServletRequest#setCharacterEncoding(String)`, "UTF-8"(specified default encoding) is applied.

Wiki page has describe the last case.

**Comment by btyamadasun** [comment]
I made a new issue about this in the internal repository and PRed.

**Comment by btyoshikawaa** [comment]
@btyamadasun 
Thx.
