### ISSUE TITLE
Packaging type of artifacts without java files should be pom

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#519]
## Description
Artifacts that are just for managing dependencies of libraries and have no java files should be pom type.
But following artifacts are set as jar type or omitted ([default type is pom](https://maven.apache.org/pom.html#Quick_Overview)).
- terasoluna-gfw-mybatis3
- terasoluna-gfw-jpa
- terasoluna-gfw-security-core

Because of the setting, we have empty jars for them.
Those are not harmful but it is confusing and may increase the cost of management of libraries.

## Possible Solutions
Set packaging type as pom.

```xml
 <packaging>pom</packaging>
```

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE

## Issue Links
* #508

**Comment by btyoshikawaa** [comment]
Leave a comment
