### ISSUE TITLE
Change the dependency on taglibs-standard-jstlel scope

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-gfw#524]
## Description
`taglibs-standard-jstlel` dependency should not be compile scope in `terasoluna-gfw-web-jsp`, because each J2ee servers should use tag libraries itself has.

## Possible Solutions
* In `terasoluna-gfw-web-jsp`, change the dependency on `taglibs-standard-jstlel` scope to `provided`.
* If run application on Tomcat, it is neccessary to add this dependency. so add this dependency in each web application projects (web blank projects, functional tests, and tour reservation).

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/301
* https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/193
* https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/246
* https://github.com/terasolunaorg/terasoluna-tourreservation/issues/379

**Comment by ikeyat** [comment]
@btyoshikawaa 
I think ``optional`` scope is more suitable for it than ``provided``.

**Comment by btyoshikawaa** [comment]
@ikeyat 
Thanks your comment.
I think `provided - optional` is more  better.
`provided` scope means it is provided by the runtime environment.
`optional` means it is not required in dependencies, used only when discovered in dependencies.

**Comment by btyoshikawaa** [comment]
For reference, now other similar liberies in `terasoluna-gfw-web-jsp` are `provided` only.

* [javax.servlet-api](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-web-jsp/pom.xml#L81)
* [javax.servlet.jsp-api](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-web-jsp/pom.xml#L86)
* [javax.el-api](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-web-jsp/pom.xml#L98)
