### ISSUE TITLE
Correct copyright phrase

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#528]
## Description
Existing copyright is ``Copyright (C) 2013-2016 terasoluna.org`` in `` license / header.txt ``.
But it should be  ~~``Copyright (C) 2013-2016 NTT DATA CORPORATION``~~ .

Updated at 2016/4/18
``Copyright (C) 2013-2016 NTT DATA Corporation`` .

## Possible Solutions
See above.

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE
- [x] 5.1.1.RELEASE
- [ ] 5.0.3.RELEASE
- [x] 1.0.5.RELEASE

**Comment by btshimizukza** [comment]
@ikeyat 

`CORPORATION` ? `Corporation` ?
In the [NTT DATA Home page](http://www.nttdata.com/global/en/index.html), company name of copyright  is `NTT DATA Corporation`.

**Comment by ikeyat** [comment]
@btmiyashitasts 
Please use ``NTT DATA Corporation`` for this.
