### ISSUE TITLE
Enable to apply the formatter  configuration to the reference projects

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-gfw#538]
## Description
Now, `formatter-maven-plugin` refer relative path to the formatter configuration file.
But If we format projects that reference the terasoluna-gfw, an error not found configuration file.
Even in these projects, it may be formatted in the same rules without any errors.

## Possible Solutions
Change the configuration file to maven project, and `formatter-maven-plugin` depend on this project.
http://code.revelc.net/formatter-maven-plugin/examples.html

If developers want to use their own configuration,It is possible to override by `pluginManagement` of their project root pom.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Issue Links
* #XXX

**Comment by ikeyat** [comment]
@btyoshikawaa 
You mean the configuration for ``terasoluna-gfw`` may also impact actual applications, right?
I'm sorry that the possible solution is unclear, but an another idea is to separate ``terasoluna-gfw-parent`` pom into for common libraries and for application in #508.

**Comment by btyoshikawaa** [comment]
@ikeyat 
Sorry, not that you mean.
I want to provide a default formatter setting, because It is hard to make the setting from scratch...

Now we can format java codes using `mvn formatter:format` in `terasoluna-gfw`.
I think it is convenient to be able to format in the actual development projects in the same way.
But now, when I create development project using terasoluna blank project and execute `mvn formatter:format`, build error (formatter xml file not found) occurs.

**Comment by ikeyat** [comment]
We will separate ``pom.xml`` for building app from ones for building common libraries at #508.
It's better to remove the configuration for formatter from the former ``pom.xml`` (it is called as ``terasoluna-gfw-xxx-dependencies``) because the configuration should not be applied for app (the formatter is not for app but for common libraries).
We will do this on #508 at the same time. So I close this.
