### ISSUE TITLE
MessagePanelTag doesn't close with </div> when it's empty

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#554]
## Description
According to W3C's spec, ``<div>`` is not listed up for the elements permitted to close with ``<xxx />``.
https://www.w3.org/TR/html5/syntax.html#elements-0

But ``MessagePanelTag`` (the class for ``<t:messagePanel>``) looks to close with ``<div />`` when it's empty (``message`` is not null but empty such as ``""`` ). It violates the rule of HTML and makes broken rendering (browsers cannot detect the end of the ``<div>``).

## Possible Solutions
Force to close with ``</div>`` to call ``tagWriter.endTag(true)`` instead of ``tagWriter.endTag()``.

https://github.com/terasolunaorg/terasoluna-gfw/blob/5.1.0.RELEASE/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java#L243

https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/tags/form/TagWriter.java#L152

## Affects Version/s
* 5.1.0.RELEASE
* ~5.0.2.RELEASE
* ~1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE
- [ ] 5.1.1.RELEASE

**Comment by ikeyat** [comment]
@kuramotoki 
Please watch this.

**Comment by kuramotoki** [comment]
@ikeyat
Thanks for your kind support.
I will add the detail at this issue after the grasp.

**Comment by kuramotoki** [comment]
@ikeyat 

This problem has been detected in the following point.

* Regardless of whether normal or error, always it set message-objects for error and info.
* If there is not value, it set an empty array.

It was solved by changing the empty array to null.
Would you tell me if you have a better workaround.

**Comment by ikeyat** [comment]
@kuramotoki 
Thanks for the information.
My understanding is that it is not supposed and not good to set empty value. It may be mis-usage.  If there is no message to show, no ``ResultMessage`` is added to model. This is a reasonable workaround.

Anyway, we had better fix this problem.

@sasakitsy 
Please assign this issue.

**Comment by btkatoutmj** [comment]
<ul> and <li> are also not listed up for the elements permitted to close with  <xxx /> .

**Comment by ikeyat** [comment]
@btkatoutmj 
Thanks. Could you check for other taglibs provided by ``terasoluna-gfw``?

**Comment by btkatoutmj** [comment]
@ikeyat 
I checked for other taglibs.

**Comment by btkatoutmj** [comment]
Following elements permitted to close with ``<xxx />``.
 * area, base, br, col, embed, hr, img, input, keygen, link, meta, param, source, track, wbr 
 * Elements from the MathML namespace and the SVG namespace.

https://www.w3.org/TR/html5/syntax.html#elements-0

**Comment by iwanagah** [comment]
@btkatoutmj  Please consider whether to add test to gfw-functional-test

**Comment by sasakitsy** [comment]
@btkatoutmj 
please fill issue of https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/459
