### ISSUE TITLE
Investigate MyBatis 3.4+ and MyBatis-Spring 1.3.0+

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#555]
## Description

MyBatis 3.4 and MyBatis-Spring 1.3.0 have been released.
https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.4.0
https://github.com/mybatis/spring/releases/tag/mybatis-spring-1.3.0
## Possible Solutions
- change `pom.xml`
- reflect what imacts exisiting guideline (create another issue in  the repos)
- add new feature guideline (create another issue in  the repos)
- reflect what imacts exisiting functionaltests and sample apps (create another issue in  the repos)
## Affects Version/s

N/A
## Fix Version/s
- 5.3.0
## Issue Links

https://github.com/terasolunaorg/guideline/issues/1777
https://github.com/terasolunaorg/guideline/issues/1776
https://github.com/terasolunaorg/guideline/issues/1775
https://github.com/terasolunaorg/guideline/issues/1695

**Comment by kazuki43zoo** [comment]
We should consider to introduce the `mybatis-typehandlers-jsr310` as framework stack.

**Comment by ikeyat** [comment]
@kazuki43zoo 
Of course Yes. It goes on #142 separately.

**Comment by ikeyat** [comment]
Even if it does not  match our version up policy of OSS libraries, we had better consider to update for not only TERA 5.2.0 but also 5.1.1.
We add the label for 5.1.1 and create a related task for it #561.

**Comment by sasakitsy** [comment]
Only for this case( from the results of #556 and #561 ), the version up policy of OSS libraries in Aug/2016 are as follows.

TERA 5.2.0  -  Spring IO Platform 2.0.x + MyBatis3.4.x + MyBatis-Spring 1.3.x
TERA 5.1.1  -  Spring IO Platform 2.0.1 + MyBatis3.3.y + MyBatis-Spring 1.2.y
("x" and "y" are going to be decided by the beginning of Constitutional test (the end of June or the early in July))

TERA 5.0.x  -  No release in Aug/2016 (because of no fatal bugs)

**Comment by kazuki43zoo** [comment]
3.4.1 has been released.

https://github.com/mybatis/mybatis-3/issues?q=is%3Aclosed%20milestone%3A3.4.1%20

**Comment by kazuki43zoo** [comment]
https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.4.1

**Comment by kazuki43zoo** [comment]
I've performed the functional test using mybatis 3.4.2-SNAPSHOT and mybatis-spring 1.3.1-SNAPSHOT.
The test results are all successful :+1:

**Comment by kazuki43zoo** [comment]
The MyBatis 3.4.2 and MyBatis-Spring 1.3.1 has been released to Maven central repository.
