### ISSUE TITLE
Inspect the impacts of MyBatis 3.4.0+

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#561]
## Description
We need to know the impacts of MyBatis 3.4.0 update.

## Possible Solutions
Simply fix the version of 
 - MyBatis from 3.3.0 to 3.4.0
 - Mybatis-Spring from 1.2.3 to 1.3.0

in the ``pom.xml`` and run the 2 functionaltests.
Then report the result.

## Affects Version/s
- 5.1.0

## Fix Version/s
TBD (determined after the inspection)

## Issue Links
* #555
* #556

**Comment by ikeyat** [comment]
This issue is limited for confirmation of regression tests and report.
Actual impacts for guideline, config and common libraries will be managed at #555

**Comment by sasakitsy** [comment]
As a result of regression tests, there is no problem by fixing the version of MyBatis.

Fixing the version of MyBatis and MyBatis-Spring in the pom.xml as follows.
(Before)
\<org.mybatis.version>3.3.0\</org.mybatis.version>
\<org.mybatis.spring.version>1.2.3\</org.mybatis.spring.version>
(After)
\<org.mybatis.version>3.4.0\</org.mybatis.version>
\<org.mybatis.spring.version>1.3.0\</org.mybatis.spring.version>

**Comment by kazuki43zoo** [comment]
Thanks for confirming !! It's good news.
Nest step, we will need to consider for changes without backward compatibility with 3.3.x.

For details, please refer to https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.4.0 .

**Comment by kazuki43zoo** [comment]
3.4.1 has been released.

https://github.com/mybatis/mybatis-3/issues?q=is%3Aclosed%20milestone%3A3.4.1%20

**Comment by ikeyat** [comment]
@sasakitsy 
I think this issue (trial) can be closed. Please continue to investigate at #555
