### ISSUE TITLE
Investigate Spring IO PF Athens(Spring 4.3 and Spring Security 4.1)

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#563]
## Description

Investigate Spring IO PF 
Athens(Spring 4.3, Spring Security 4.1, etc) for 5.3.0 release.
## Possible Solutions

Investigate main changes and impact to framework stack, common libraries and guideline.
## Affects Version/s

-
## Fix Version/s
- [x] 5.3.0
## Issue Links
- #510
- #523
- https://github.com/terasolunaorg/guideline/issues/1633
- https://github.com/terasolunaorg/guideline/issues/1705
- https://github.com/terasolunaorg/guideline/issues/1704
- https://github.com/terasolunaorg/guideline/issues/1293

**Comment by kazuki43zoo** [comment]
I've confirmed main changes for Spring 4.3 and Spring Security 4.1 at  the moment. For details, refer to following pages (Japanese Only):

* http://qiita.com/kazuki43zoo/items/172d132ff8f4ba098888
* http://qiita.com/kazuki43zoo/items/e925f134e65d7595aa3c

**Comment by ikeyat** [comment]
Spring 4.3 has been released
 http://spring.io/blog/2016/06/10/spring-framework-4-3-goes-ga
 https://docs.spring.io/spring-framework/docs/4.3.x/spring-framework-reference/htmlsingle/#new-in-4.3

There is no update on Spring IO Platform now. Spring IO Platform 2.1.x will update Hibernate 4.3 to 5.2    and that may impact to our JPA resources.

**Comment by ikeyat** [comment]
Spring Security 4.1.2 has been released. Bugs around ``MvcPathMatcher``  were fixed.
Currently, Spring IO Platform Athens does not include it yet.

**Comment by ikeyat** [comment]
Spring IO PF Athens is planned to be released on September 15, 2016.
https://github.com/spring-io/platform/milestone/26

Please keep attention.

**Comment by ikeyat** [comment]
@btryuushou 
Spring IO PF Athens has not been released.
But we would like to prepare for this.

- [ ] Try to build ``terasoluna-gfw`` with latest SNAPSHOT version in a working branch.
- [ ] Try to run functionaltest with the ``terasoluna-gfw``  built with Spring IO PF Athens SNAPSHOT.
- [ ] Create issues if you found problems in those steps.

**Comment by kazuki43zoo** [comment]
Spring IO PF Athens has been released !!

**Comment by btyoshikawaa** [comment]
@sasakitsy 
Already applyed! Please confirm remain tasks.

**Comment by kazuki43zoo** [comment]
The Athens-SR2 has been released !
See https://spring.io/blog/2017/01/04/spring-io-platform-athens-sr2.

* https://jira.spring.io/jira/secure/ReleaseNote.jspa?projectId=10000&version=15779
* https://github.com/spring-projects/spring-security/milestone/94?closed=1

**Comment by itouyun** [comment]
調査は終わった認識なので、本issueはクローズします。
調査の横展開issueは既に起票済のため、各対応は各issueにて行うこととする。
