### ISSUE TITLE
TransactionToken does not support some special flows

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#565]
## Description
TBD

## Possible Solutions
TBD

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.0-5.0.2.RELEASE
* 1.0.0-1.0.4.RELEASE

## Fix Version/s

API Draft for 5.2.0.RC1 and 5.1.1.RC1
- [x] 5.2.0.RC1
- [x] 5.1.1.RC1

Polish Javadoc
- [x] 5.2.0.RELEASE
- [x] 5.1.1.RELEASE

Final
- [x] 5.2.0.RELEASE
- [x] 5.1.1.RELEASE

## Issue Links
* #564

**Comment by sasakitsy** [comment]
The remaining issues will be resolved in following issue.
https://github.com/terasolunaorg/guideline/issues/1967

**Comment by btyoshikawaa** [comment]
@btkobayashirun 
Please backport #608 to 5.1.x .
