### ISSUE TITLE
Remove mvn-build-all.sh and .bat

### ISSUE THREAD

**Issue by bttanakagn** [terasolunaorg/terasoluna-gfw#567]
## Description
Now, we use `mvn-build-all.sh` and .bat but they will be unneccessary if include the `terasoluna-gfw-dependencies` and `terasoluna-gfw-parent` in the root module.

## Possible Solutions
Include following projects in root module(terasoluna-gfw).
* `terasoluna-gfw-dependencies`
* `terasoluna-gfw-parent`

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/508

**Comment by kazuki43zoo** [comment]
We wil modify `.travis` on [terasoluna-gfw-functionaltest](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest) and [terasoluna-tourreservation](https://github.com/terasolunaorg/terasoluna-tourreservation) and more...

**Comment by kazuki43zoo** [comment]
@sasakitsy 

Please assign to someone.

**Comment by ikeyat** [comment]
- [ ] Need tp refactor  https://github.com/terasolunaorg/terasoluna-gfw/issues/508#issuecomment-229638734
