### ISSUE TITLE
Remove SonarQube Warning

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/terasoluna-gfw#582]
## Description
One Blocker and one Critical warning increase by the rule change of the latest SonarQube.
It's necessary to be settled.

## Possible Solutions
Fix them as following SonarQube report.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0
- [x] 5.1.1

## Issue Links
* #XXX

**Comment by btyoshikawaa** [comment]
@btnoguchimnm 
Please backport to 5.1.x .
