### ISSUE TITLE
createToken() of TransactionTokenContextImpl does not work properly

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw#593]
## Description
Transaction token libiraries provide some APIs for programatic operation for the extensibility.
But some APIs may lead illegal status.
The APIs  is rarely used because of the necessity. The best solution seems to deprecate them.

## Possible Solution
- Deprecate APIs that are provided by ``TransactionTokenContext`` and ``TransactionTokenContextImpl``.

## Fix Versions
- [x] 5.2.0
- [x] 5.1.1

## Issue Links
* https://github.com/terasolunaorg/guideline/issues/1995

**Comment by ikeyat** [comment]
Leave a comment
