### ISSUE TITLE
Upgrade to license-maven-plugin provided by mycila

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#600]
## Description

Currently, we use the `com.google.code.maven-license-plugin:maven-license-plugin:1.4.0`. However, it move to the `com.mycila:license-maven-plugin`.
## Possible Solutions

Modify to use the `com.mycila:license-maven-plugin`.
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE
## Fix Version/s

(To be written later by project member)
## Issue Links
- http://code.mycila.com/license-maven-plugin/
- http://qiita.com/kazuki43zoo/items/4ccad9120778dbf21f5c (Japanese only)

**Comment by btkatoufm** [comment]
Fix in https://github.com/terasolunaorg/terasoluna-gfw/issues/1083
