### ISSUE TITLE
Improve unit testing coverage

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#611]
## Description

For keeping quality and compatibility, the coverage of unit testing should be increased as possible.
For example, a following constructor need to be covered. 

```
public BusinessException(String message)
```

https://coveralls.io/github/terasolunaorg/terasoluna-gfw?branch=release%2F5.2.0.RC7
## Possible Solutions

TBD
## Affects Version/s
- 5.2.0.RELEASE
- ~5.1.1.RELEASE
- ~5.0.2.RELEASE
- ~1.0.5.RELEASE
## Fix Version/s
- [x]  5.3.0.RELEASE
- [x]  5.2.1.RELEASE
- [ ]  5.1.2.RELEASE
- [ ]  5.0.3.RELEASE
- [ ]  1.0.6.RELEASE

**Comment by btyoshikawaa** [comment]
@btsuzukittm 
Please backport!

**Comment by kazuki43zoo** [comment]
@sasakitsy @ikeyat  @btyoshikawaa

Do you need to backport to all versions(5.2.x, 5.1.x, 5.0.x, 1.0x) ?

**Comment by btyoshikawaa** [comment]
@kazuki43zoo @sasakitsy ( @ikeyat )
I think we need to backport to the 1 maintenance version ( 5.2.x ).
