### ISSUE TITLE
Update version in README.md

### ISSUE THREAD

**Issue by btkatoutmj** [terasolunaorg/terasoluna-gfw#613]
## Description
Update version to 5.2.0.RELEASE in master and 5.2.x
Update version to 5.1.1.RELEASE in 5.1.x
Update version to 1.0.5.RELEASE in 1.0.x
fix travis-ci badge in README.md on 5.2.x

## Possible Solutions
 -

## Affects Version/s
 -

## Fix Version/s
- [x] 5.3.0(master)
- [x] 5.2.1(5.2.x)
- [x] 5.1.2(5.1.x)
- [x] 1.0.6(1.0.x)
- [x] 5.2.x(travis-ci badge, coverall badge)

## Issue Links
Nothing

**Comment by btkatoutmj** [comment]
fix travis-ci badge in README.md on 5.2.x

branch=master -> branch=5.2.x

**Comment by ikeyat** [comment]
Not only travis-ci badge, but also coverall badge.

**Comment by btyoshikawaa** [comment]
@btkatoutmj @btyanagawamg 
Thx!
