### ISSUE TITLE
Polish code style

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#627]
## Description

Review #626 and import or re-polish if required.
## Possible Solutions

N/A
## Affects Version/s
- 5.2.0.RELEASE
- ~5.1.1.RELEASE
- ~5.0.2.RELEASE
- ~1.0.5.RELEASE
## Fix Version/s
- [ ] 5.3.0.RELEASE
- [ ] 5.2.1.RELEASE
- [ ] 5.1.2.RELEASE
- [ ] 5.0.3.RELEASE
- [ ] 1.0.6.RELEASE
## Issue Links
- #626

**Comment by kazuki43zoo** [comment]
@sasakitsy 

Please decide scope.

**Comment by btkatoufm** [comment]
ISSUE has a large scope, so please name what the problem is with the smaller scope.
