### ISSUE TITLE
Consider elimination of the cord

### ISSUE THREAD

**Issue by btmikamiysy** [terasolunaorg/terasoluna-gfw#633]
## Description
TERASOLUNA Server Framework is using Spring4.
but,The following code considers use of Spring 3.
So, please consider the following cord elimination.

[...terasoluna-gfw-web/.../mvc/support/ProcessActionInvocationHelper.java](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/mvc/support/ProcessActionInvocationHelper.java)
```
         if (targetProcessActionMethod == null) { 
             // Check Spring3's signature 
             targetProcessActionMethod = ReflectionUtils.findMethod( 
                     RequestDataValueProcessor.class, "processAction", 
                     HttpServletRequest.class, String.class); 
             isLegacySignatureTmp = true; 
         } 
```
If it's eliminated, consider change in the part affected by elimination.
```
        if (isLegacySignature) {
```
(Please write the problem in detail)

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.2.0.RELEASE
* ~5.1.1.RELEASE
* ~5.0.2.RELEASE
## Fix Version/s
(To be written later by project member)

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/611

**Comment by kazuki43zoo** [comment]
Out of scope for 2017 winter.

**Comment by itouyun** [comment]
Possible Solutions.
5.0.x~ 

1. elimination
```
        if (targetProcessActionMethod == null) {
            // Check Spring3's signature
            targetProcessActionMethod = ReflectionUtils.findMethod(
                    RequestDataValueProcessor.class, "processAction",
                    HttpServletRequest.class, String.class);
            isLegacySignatureTmp = true;
        }
```
```
    /**
     * Flag that indicate whether legacy signature.
     */
    private final boolean isLegacySignature;
```
and `isLegacySignatureTmp` ...

2. change
```
        if (isLegacySignature) {
            return (String) ReflectionUtils.invokeMethod(
                    this.processActionMethod, requestDataValueProcessor,
                    request, action);
        } else {
            return (String) ReflectionUtils.invokeMethod(
                    this.processActionMethod, requestDataValueProcessor,
                    request, action, method);
        }
```
to
```
        return (String) ReflectionUtils.invokeMethod(
                this.processActionMethod, requestDataValueProcessor,
                request, action, method);
```

**Comment by btkatoufm** [comment]
Please backport with a new issue if needed.
