### ISSUE TITLE
@Compare don't display error message for left property in certain cases

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-gfw#634]
## Description
For example set as follows, if use `@Compare` with attribute `requiredBoth` is `true` and `node` is `PROPERTY` (default).
```java
@Compare(left = "email", right = "confirmEmail",
    operator = Compare.Operator.EQUAL,
    requireBoth = true)
public class UserRegisterForm {
    private String email;
    private String confirmEmail;
}
```
When either left property or right property is null, error message is not desplayed.
Because error message is desplayed as `ROOT_BEAN` message unintentionally.

## Possible Solutions
https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/CompareValidator.java#L100
Also in the case of that `(leftValue == null && rightValue == null)` return `false`, it should be called `CompareValidator#constructValidationMessage`.

## Affects Version/s
* 5.1.0.RELEASE and later

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2

## Issue Links
* #XXX

**Comment by kazuki43zoo** [comment]
Hi @yoshidatkw , Are there not need a modification on the [integration test](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest) ?

**Comment by kazuki43zoo** [comment]
Hi @yoshidatkw , Sorry i've mistaken the destination of mention.

**Comment by kazuki43zoo** [comment]
Hi @btyoshikawaa , Are there not need a modification on the [integration test](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest) ?

**Comment by kazuki43zoo** [comment]
@yoshikawaa 

ping for about above question.

**Comment by yoshikawaa** [comment]
@kazuki43zoo 
I think that the E2E test is unnecessary, because unit test can ensure sufficient code quality for this problem.

**Comment by kazuki43zoo** [comment]
@yoshikawaa 

OK !
