### ISSUE TITLE
Improve CodelistInterceptor's performance to filter target requests

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-gfw#636]
## Description
Currently ``CodelistInterceptor`` performs to scan codelists and put all codelist's content into request scope for all requests.
That may cause a performance problem when an app has many codelists.

There is no way to predict which codelists will be used in JSP rendering correctly.
However, it is obvious they must not be used for some certain targets (eg. static resources, JSON).

## Possible Solutions
- Validate which the requests may use codelist or not. (eg. analyze Content-Type in ``HttpServletRequest`` or ``handler``, etc...)
- (Alternative solution) Restrict url pattern configuration of ``CodelistInterceptor`` in blank project. Warning it on the guideline.

## Affects Version/s
* 5.2.0.RELEASE
* ~5.1.1.RELEASE
* ~5.0.2.RELEASE
* ~1.0.5.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0 (master)
- [ ] 5.3.1 (5.3.x)

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #XXX

**Comment by ikeyat** [comment]
Currently, static targets are excluded in the default config in blank project. But there is room to exclude.

https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/blob/5.2.0.RELEASE/projectName-web/src/main/resources/META-INF/spring/spring-mvc.xml#L53

**Comment by kazuki43zoo** [comment]
As other solution, there is the way to use bean reference using `<spring:eval expression="@...">` on demand.

**Comment by ikeyat** [comment]
@kazuki43zoo 
Do you mean to use ``<spring:eval expression="@...">`` instead of using ``CodelistInterceptor`` and general JSP tag, right?

**Comment by kazuki43zoo** [comment]
@ikeyat 

Yes, i think a one idea for resolving this issue. But i don't know whether it is the good solution or not yet ...
I will consider more solution.
