### ISSUE TITLE
Update to cargo-maven2-plugin 1.6.2

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#646]
## Description
Update to latest version.

## Affects Version/s
All versions

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6

---
Change property key for specifying a URIEncoding.

- [x] 5.3.0
- [x] 5.2.1
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.6

## Issue Links
\-

**Comment by kazuki43zoo** [comment]
We should be changed the property key for specifying a URIEncoding to `cargo.tomcat.uriencoding` from `cargo.servlet.uriencoding`.

**Comment by btyoshikawaa** [comment]
see https://groups.google.com/forum/#!topic/codehaus-cargo/VKmOUF-QzWM .
