### ISSUE TITLE
Remove SonarQube Warning

### ISSUE THREAD

**Issue by sasakitsy** [terasolunaorg/terasoluna-gfw#663]
## Description
"Blocker" and "Critical" warnings increase by the rule change of the latest SonarQube.
It's necessary to be settled.

## Possible Solutions
Fix them as following SonarQube report.

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.2.1
- [x] 1.0.6

## Issue Links
* #XXX

**Comment by btfurukawatkr** [comment]
checked the issues for 5.2.1, nothing to fix

**Comment by sasakitsy** [comment]
checked the issues for 5.3.0, nothing to fix
