### ISSUE TITLE
Modify pom.xml related to "Maven Central" migration

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/terasoluna-gfw#664]
# Description
We need to modify pom.xml when migrate to "Maven Central".

## Possible Solutions
Make the following modifications to "/pom.xml"
 - [x] remove "distributionManagement" tag in "default" profile
 - [x] remove repositories

Make the following modifications to "/terasoluna-gfw-parent/pom.xml "
 - [x] remove "distributionManagement" tag in "default" profile

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
 - [x] 5.3.0

## Issue Links
* #620 
* https://github.com/terasolunaorg/guideline/issues/2444
* https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/297
* https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/263

**Comment by kazuki43zoo** [comment]
@bthayashidi 

> add the following snapshot repository settings

Is need this fix ?

**Comment by bthayashidi** [comment]
Ah, certainly no need is this.
I will fix "Possible Solutions".
