### ISSUE TITLE
Consider to drop Travis CI for Oracle JDK 7

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#666]
## Description

We use the Open JDK for building this artifacts. Hence I think we can drop a build that used the Oracle JDK 7 on Travis CI.

## Possible Solutions

Drop `oraclejdk7` from `.travis.yml`.

## Affects Version/s
* All versions

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Issue Links
- http://www.oracle.com/technetwork/jp/java/eol-135779.html

**Comment by itouyun** [comment]
Thank you for your rapid work!
This issue is closed.
