### ISSUE TITLE
code format for 2017 winter release

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/terasoluna-gfw#674]
## Description
execute code format 

## Possible Solutions
mvn formatter:format

## Affects Version/s
* 5.3.0.RELEASE
* 5.2.1.RELEASE
* 5.1.2.RELEASE
* 5.0.3.RELEASE
* 1.0.6.RELEASE

## Fix Version/s
* Must
- [x] 5.3.0.RELEASE
- [x] 5.2.1.RELEASE
- [x] 1.0.6.RELEASE

* Low Pri.
- [x] 5.1.2.RELEASE
- [x] 5.0.3.RELEASE

## Issue Links
*

**Comment by kazuki43zoo** [comment]
finished for must task.
