### ISSUE TITLE
Upgrade to maven-staging-plugin 1.6.8

### ISSUE THREAD

**Issue by btishiwatasns** [terasolunaorg/terasoluna-gfw#683]
## Description
using a buggy version.
can not go through the proxy. I am making interim measures.
It solves by upgrading.

## Possible Solutions
parent pom.xml
<nexus-staging-maven-plugin.version>1.6.7</nexus-staging-maven-plugin.version> -> 1.6.8

## Affects Version/s
* 5.3.x.RELEASE

## Fix Version/s
- [x] 5.4.0.RELEASE
- [x] 5.3.2.RELEASE
- [x] 5.2.2.RELEASE

## Issue Links

* https://issues.sonatype.org/browse/NEXUS-10502
* https://github.com/sonatype/nexus-public/pull/23
* https://github.com/sonatype/nexus-maven-plugins/pull/84

**Comment by kazuki43zoo** [comment]
done!

**Comment by yoshikawaa** [comment]
@btkobayashirun Please fix also 5.2.x branch.
