### ISSUE TITLE
Update SNAPSHOT version (2017 winter)

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/terasoluna-gfw#685]
## Description

Update version to 5.4.0-SNAPSHOT in master
Update version to 5.3.1-SNAPSHOT in 5.3.x
Update version to 5.2.2-SNAPSHOT in 5.2.x
Update version to 1.0.7-SNAPSHOT in 1.0.x
## Fix Version/s
- [x] master
- [x] 5.3.x
- [x] 5.2.x
- [x] 1.0.x

**Comment by yoshikawaa** [comment]
@sasakitsy 
If versioning is OK, close this issue.
