### ISSUE TITLE
Improve java code format

### ISSUE THREAD

**Issue by btkatoutkm** [terasolunaorg/terasoluna-gfw#698]
## Description
Now, java code format is collapsed often.
This makes it difficult to merge the souce code.

## Possible Solutions
*  Modify java code format (use formatter-maven-plugin)
*  Check java code format on travis (use formatter-maven-plugin)

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [ ] 5.4.0.RELEASE

## Issue Links
* #680

**Comment by yoshikawaa** [comment]
@btkatoutkm 
Is this issue need?

> * Modify java code format (use formatter-maven-plugin)

This is already in operation.
(Please see [terasoluna-gfw-common-libraries/pom](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-common-libraries/pom.xml#L90-L99))

> * Check java code format on travis (use formatter-maven-plugin)

It will be supported by #680 .

I think, you should close this, or extend the scope other than `java`.

**Comment by btkatoutkm** [comment]
@yoshikawaa 
OK. I close this issue.
