### ISSUE TITLE
Log level specification method is not unified

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw#702]
## Description
Now, The TERASOLUNA common library is providing two ways for exception logging.
Unfortunately, the log level specification way differs between them.

1. Logging inside `HandlerExceptionResolver` is Intercepted, determined by **HTTP status code**. 
    * [HandlerExceptionResolverLoggingInterceptor](/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/HandlerExceptionResolverLoggingInterceptor.java#L203-L228)
2. Logging inside `ServletFilter`, determined by **specified exception code**.
    * [ExceptionLoggingFilter](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/exception/ExceptionLoggingFilter.java#L150)
      - [ExceptionLogger](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/ExceptionLogger.java#L273)
        - [DefaultExceptionLevelResolver](https://github.com/terasolunaorg/terasoluna-gfw/blob/master/terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/exception/DefaultExceptionLevelResolver.java#L69-L81)
## Possible Solutions
We need to consider.
For example, prioritize the exception code and see the status code if it is not set?

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)

## Issue Links
* #XXX

**Comment by bttanakaysd** [comment]
## Decision

1. The log level of `HandlerExceptionResolverLoggingInterceptor` is not changed.
   * This is because it is difficult to determine the log level depending on the requirements of each project and to satisfy all the requirements with a common library.
   
2. We decided to change the log level of `ExceptionLoggingFilter` to ERROR.
   * This change is to make it consistent with the description of the guidelines.

**Comment by yoshikawaa** [comment]
Based on https://github.com/terasolunaorg/terasoluna-gfw/issues/702#issuecomment-308613031 , I have organized the fix version.
