### ISSUE TITLE
Cannot validate "not equal" using @Compare

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#711]
## Description
In current implementation, it supports following 5 operators, however these operator cannot represent "not equal".

* less than
* less than or equal
* equal
* greater than
* greater than or equal

For example, I want to use "not equal"  for validating password(validating different with other item value like "Account ID", "Date of birth" and more ...).

## Possible Solutions
Add `NOT_EQUAL` operator on `@Compare`.

## Affects Version/s
* 5.1.0.RELEASE +

## Fix Version/s
* [x] 5.4.0 (master)
* [x] 5.3.1 (5.3.x)

## Issue Links
* #XXX

## Migration Guide
* Not Required

**Comment by yoshikawaa** [comment]
@itouyun 
I think this suggestion is supplementation of missing features rather than a new function, and should also be included in the maintenance release (5.3.1).

**Comment by itouyun** [comment]
@yoshikawaa 
I think so, too.

@kazuki43zoo 
Please backport 5.3.1(5.3.x).

**Comment by kazuki43zoo** [comment]
> And please backport 5.3.1(5.3.x).

ok.
