### ISSUE TITLE
Drop dependency for mybatis-typehandlers-jsr310 when upgrade to MyBatis 3.4.5+

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#715]
## Description
MyBatis 3.4.5+ supports type handlers for JSR-310 Date and Time API as core module. Therefore we can drop mybatis-typehandlers-jsr310  from terasoluna-gfw-mybatis3-dependencies and parent pom.

Note: MyBatis 3.4.5 not released yet at the point of 2017-07-10.

## Possible Solutions
Drop dependencies for mybatis-typehandlers-jsr310.

## Affects Version/s
\-

## Fix Version/s
- [x] 5.4.0

## Issue Links
* mybatis/mybatis-3#974
* terasolunaorg/guideline#2839
* #732

**Comment by itouyun** [comment]
terasolunaorg/guideline#2839 と同時リリース。

**Comment by kazuki43zoo** [comment]
The mybatis 3.4.5 has been released at today!
