### ISSUE TITLE
Add 'Migrating Guide' section to Issue Template

### ISSUE THREAD

**Issue by btkamiyae** [terasolunaorg/terasoluna-gfw#718]
## Description
This is maintenance task.
Now, it's hard to judge from issue description whether a task in one Issue contains a Migrating Guide.

## Possible Solutions
Add new section Migrating Guide.
 Make it possible to choose from  correspond  or  not correspond(create new issue).

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] master

Backport is not necessary. 
Because only `ISSUE_TEMPLATE.md` of `master` branch is affected.
~~- [ ] 5.3.x~~
~~- [ ] 5.2.x~~
~~- [ ] 5.1.x~~
~~- [ ] 5.0.x~~
~~- [ ] 1.0.x~~

## Issue Links
* #XXX

**Comment by itouyun** [comment]
Backport is not required.
Thank you for working.
This issue is closed.
