### ISSUE TITLE
Consider to drop Travis CI for Open JDK 6

### ISSUE THREAD

**Issue by btkamiyae** [terasolunaorg/terasoluna-gfw#725]
## Description
We use the Open JDK for building this artifacts. Hence I think we can drop a build that used the Open JDK 6  on Travis CI.

https://access.redhat.com/articles/1299013

## Possible Solutions
Drop `OpenJDK 6`  from  `.travis.yml` .
Drop `if [[ $TRAVIS_JDK_VERSION != "openjdk6" ]]; `  from  `.travis.yml` .

## Affects Version/s
* 5.0.x
* 1.0.x
## Fix Version/s
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Issue Links
* #666

**Comment by itouyun** [comment]
Thank you for your rapid work!
This issue is closed.
