### ISSUE TITLE
Consider to upgrade to Dozer 6.x 

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#731]
## Description
[Dozer 6.x](https://github.com/DozerMapper/dozer/releases) has been released already.
(However, it requires Java 8)

## Possible Solutions
Please consider upgrading dependency version or introducing a new version on development guideline.

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [ ] 5.4.0 (master)
- [ ] 5.3.1 (5.3.x)

## Migrating Guide
- [ ] Required

## Issue Links
- [migration guide](https://github.com/DozerMapper/dozer/tree/master/docs/asciidoc/migration)
- #823

**Comment by ikeyat** [comment]
This is a good news! 
Actually I had given it up for dead.

**Comment by itouyun** [comment]
Spring IO Platform is not support Dozer.
We consider upgrading dependency version positively and uniquely.
- check difference of 5.x to 6.x
- consider updating guideline
- consider upgrading dependency version on sume pom
- consider introducing version of TERASOLUNA

**Comment by yoshikawaa** [comment]
@itouyun 
If we are considering upgrading Dozer, it's necessary to make TERASOLUNA support JDK version upper 1.8.

**Comment by itouyun** [comment]
Ummmm.
It's not very well that next version framework will update necessary JDK version because of only Dozer.
We consider https://github.com/terasolunaorg/terasoluna-gfw/issues/731#issuecomment-324816314  as fast as we can. But we will not maybe update Dozer for TERASOLUNA 5.4.0.

**Comment by kazuki43zoo** [comment]
I tried the Dozer 6.1.0 using [spring-functionaltest](https://github.com/Macchinetta/spring-functionaltest) provided by the Macchinetta. The `BeanMappingTest` is working fine!!

e.g.)
```
$ mvn -U test -pl spring-functionaltest-selenium -Dtest=BeanMappingTest
```

Changes see [here](https://github.com/kazuki43zoo/spring-functionaltest/commit/d7cd81039cfc3204e5981c5b3329733d87a2ea79).

**Comment by btkatoufm** [comment]
done at #823
