### ISSUE TITLE
Upgrade to MyBatis 3.4.5

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#732]
## Description
The MyBatis 3.4.5 has been released at today.
See release note:

* https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.4.3
* https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.4.4
* https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.4.5

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)

## Migrating Guide
- Not Required

## Issue Links
- #715
- terasolunaorg/guideline#2839

**Comment by yoshikawaa** [comment]
Thanks @kazuki43zoo .
