### ISSUE TITLE
Add description for terasoluna-gfw-codepoints to README.md.

### ISSUE THREAD

**Issue by btsatouhrzzp** [terasolunaorg/terasoluna-gfw#734]
## Description
In using `terasoluna-gfw-codepoints`, it is difficult to understand that there are 5 `terasoluna-gfw-codepoints`.

- only description of `terasoluna-gfw-codepoints` now
https://github.com/terasolunaorg/terasoluna-gfw/blob/b9de839e08682c51796a15d345032a22755efc92/README.md#L92-L96
https://github.com/terasolunaorg/terasoluna-gfw/blob/b9de839e08682c51796a15d345032a22755efc92/README.md#L186-L191

- there are not another 4 codepoints description
  - terasoluna-gfw-codepoints-jisx0201
  - terasoluna-gfw-codepoints-jisx0208
  - terasoluna-gfw-codepoints-jisx0208kanji
  - terasoluna-gfw-codepoints-jisx0213kanji

## Possible Solutions
Add another 4 `terasoluna-gfw-codepoints-@@@`.

## Affects Version/s
- 5.1.0.RELEASE and later

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)

## Final Solution
do Possible Solution

## Migrating Guide
- Not Required

## Issue Links
- https://github.com/terasolunaorg/guideline/issues/2785 (same timing release)

**Comment by yoshikawaa** [comment]
@itouyun @bttsuchikawaf 
https://github.com/terasolunaorg/terasoluna-gfw/tree/5.1.x/terasoluna-gfw-codepoints/catalog
It seems better to apply this to 5.1.x.

https://github.com/terasolunaorg/terasoluna-gfw/blob/5.1.x/README.md
However, since 5.1.x lacks descriptions such as `codepoints` `validator` `string`, we need to add them as well.

How do you think?

**Comment by yoshikawaa** [comment]
@itouyun @bttsuchikawaf 
Please see https://github.com/terasolunaorg/terasoluna-gfw/issues/734#issuecomment-332113178, I added 5.1.x to the target.

**Comment by itouyun** [comment]
@yoshikawaa 
I think so, too.
5.1.x problem of lacks descriptions should be deal by this issue.
