### ISSUE TITLE
Support openjdk8 on Travis CI

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#739]
## Description

The Ubuntu trusty has been supported openjdk8 as JDK type.

## Possible Solutions
Adding `openjdk8` in `.travis.yml`.

```diff
jdk:
  - oraclejdk8
+  - openjdk8
  - openjdk7
```

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Final Solution
See Possible solutions.

## Migrating Guide
- Not Required

## Issue Links
- #666

**Comment by itouyun** [comment]
Should we do all version?

**Comment by kazuki43zoo** [comment]
> Should we drop oraclejdk8?

On Travis CI, I think that it is enough to perform test with openjdk.
But, you should decide according to your organization's policies for test on Travis CI.

Note: Public Updates of Oracle JDK 8 plant to end at Sep 2018(about one year later). For details, see [Oracle Java SE Support Roadmap](http://www.oracle.com/technetwork/jp/java/eol-135779.html).

**Comment by itouyun** [comment]
Timing of support JDK type is different in openjdk and oraclejdk by the Ubuntu trusty.
We should check next JDK version as soon as possible.

- conclusion (policies)
  - We should check double JDK type of `openjdk` and `oraclejdk` for test on Travis CI.
    - If CI time is so long long long, we should replace `oraclejdk` for `openjdk`, in other words we should drop `oraclejdk` before EOL.
  - We should drop JDK when the time of EOL comes.
  - We should update all version branches.

**Comment by itouyun** [comment]
Now, CI time is not very long, We whould check double JDK.

Final solution of this issue is @kazuki43zoo 's possible solutions.

**Comment by yoshikawaa** [comment]
@kazuki43zoo Thanks!
