### ISSUE TITLE
Update tomcat.version for cargo 

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#741]
## Description
Currently, it is 8.0.39. But Spring IO Platform depends on 8.5.x (latest Athens: 8.5.15, latest Brussels: 8.5.20). 

https://github.com/terasolunaorg/terasoluna-gfw/blob/399d87efadce42d78a7e9a908015e750bc35ed1d/terasoluna-gfw-parent/pom.xml#L422

> **Note:**
> 8.0.x line will be EOL at 30 June 2018. For details refer to [here](https://tomcat.apache.org/tomcat-80-eol.html).

## Possible Solutions
I propose to upgrade to the version same with Spring IO Platform (= latest version of 8.5.x line).

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)

## Final Solution
(To be written later by project member)

## Migrating Guide
- [ ] Required

## Issue Links
- #XXX

**Comment by itouyun** [comment]
Thank you for making issue.
We need to update that on 5.4.0 with Brussels only.
