### ISSUE TITLE
Maven plugins are older

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#742]
## Description

Many Maven plugins managed by parent pom are older.

| Plugin | Current | Latest | Remark |
| ------- | :---------: | :------: | ---------- |
| maven-compiler-plugin | 3.1  | 3.7.0 | |
| maven-dependency-plugin | 2.9 | 3.0.2 | |
| maven-resources-plugin | 2.6 | 3.0.2 | |
| maven-source-plugin | 2.4 | 3.0.1 | |
| maven-javadoc-plugin | 2.10.1 | 2.10.4 | has been released 3.x milestone version |
| maven-jar-plugin | 2.5 | 3.0.2 |
| maven-assembly-plugin | 2.5.1 | 3.1.0 |
| maven-clean-plugin | 2.5 | 3.0.0 |
| maven-site-plugin | 3.4 | 3.6 |
| cargo-maven2-plugin | 1.6.2 | 1.6.4 |

## Possible Solutions

I hope to update plugin version as much as possible.

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0 (master)
- [ ] 5.3.1 (5.3.x)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #812

**Comment by itouyun** [comment]
Thank you for you making issue.
We will consider updating for Maven plugin and release timing.

**Comment by btkatoufm** [comment]
This issue has been resolved in https://github.com/terasolunaorg/terasoluna-gfw/issues/1010.
Thank you.
