### ISSUE TITLE
f:query and f:u not work correctly on Spring Framework 5

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#757]
## Description
I tried to apply the CAIRO-BUILD-SNAPSHOT (includes Spring Framework 5), it failed some tests as follow:

```
Results :

Failed tests: 
  FunctionsTest.testU_EncodingDelimiter:320 
Expected: is "%2B"
     but: was "+"
  FunctionsTest.testQuery04_url_encoding_for_queryString:545 
Expected: is "key%231=value%231&key%5B2=value%5B2&key%5D3=value%5D3&key%264=value%264&key%3D5=value%3D5&key%2B6=value%2B6"
     but: was "key%231=value%231&key%5B2=value%5B2&key%5D3=value%5D3&key%264=value%264&key%3D5=value%3D5&key+6=value+6"
```

In Spring 4, `+`(`0x2b`) is encoding to `%2B`, But Since Spring 5, it does not encode to `%2B`.
If send `+`  to Servlet container such as the Tomcat, it decodes to `0x20`(half space) rather than `0x2b`(`+`).

This issue related with [SPR-14828](https://jira.spring.io/browse/SPR-14828) .

## Possible Solutions

**TBD**. However, I suggest adding a note or warning for Spring Framework 5 on README or development guideline until supporting Spring Framework 5 as framework stack.

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0 (master)

## Issue Links
- https://jira.spring.io/browse/SPR-14828

**Comment by btournc** [comment]
@hirakuriy  @yoshikawaa 
Fix it below.
#820 5.Fix failed tests of Spring

**Comment by yoshikawaa** [comment]
@btournc [Conclusion of SPR-14828](https://jira.spring.io/browse/SPR-14828?focusedCommentId=154585&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-154585)
We need to consider alternatives to `UriComponentsBuilder`, `UriUtils.encodeQueryParam`.

**Comment by yoshikawaa** [comment]
@hirakuriy @bttanakaysd 
Merged.
You have to modify the apps (functional tests, sample apps) to accommodate this change.
And you have to write about this change in the migration guide.
