### ISSUE TITLE
Suggest to add constraint annotation that validate a byte size range

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#761]
## Description

Currently, terasoluna-validator provide `@ByteMin` and `@ByteMax` for validating byte size.Theses annotations are working fine, However if I want to validate byte size range of string, I need to specify a two annotation as folllows:

```java
@ByteMin(2)
@ByteMax(20)
private String name;
```

In other words, it perform converting twice to the same byte arrray from same string.
I think it's a wasteful processing.
Therefor I suggest to add the constraint annotation such as `@ByteSize` that can be specified the `min` and `max` attribute at the same time.

e.g. )
```java
@ByteSize(min = 2, max = 20)
private String name;
```

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.1 (master)
- [x] 5.4.2 (5.4.x)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #372

**Comment by yoshikawaa** [comment]
@kazuki43zoo 
I think that it is a very attractive suggestion.

However as you also know, when creating @ ByteMin and Max, we have decided to provide only the necessary minimum functions as TERASOLUNA common library since range checking can be realized by using two annotations.
It will be provided after considering whether it is really necessary as a TERASOLUNA common library.

Thanks.

**Comment by kazuki43zoo** [comment]
@yoshikawaa Thanks for quick response!

I understand your opinion and the current API specification is no problem :) 
But I though the `@ByteSize` is more reasonable rather than `@ByteMin`/`@ByteMax`,
because it can be used like same with `@Size` that validate character size(min, max and range).

I would be happy if there is opportunity that your team reconsider again for this topic.
Thanks.

**Comment by yoshikawaa** [comment]
[For Project Members]
In discuss, see https://github.com/terasolunaorg/terasoluna-gfw/pull/762#issuecomment-336003077.

**Comment by kazuki43zoo** [comment]
I've submitted PR to the Hibernate Validator that adding the `@CodePointLength` for validating a code point length of a specified `CharSequence`(`String`, `StringBuilder` and so on ...). Probably, it will be merge into Hibernate Validator 6.0 line.
I suggest to submit PR that adding `@ByteSize` (or `@ByteLength`) to the Hibernate Validator!

See https://hibernate.atlassian.net/browse/HV-1496.

**Comment by yoshikawaa** [comment]
@hirakuriy Pending until 5.5.0.RC2-development branch is merged.
