### ISSUE TITLE
When support Java 9(or 18.3+) ?

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#771]
## Description
The Oracle has been announced [the roadmap for Java SE supports](http://www.oracle.com/technetwork/jp/java/eol-135779.html).
The Java SE 8 will finish the Public update at September 2018. and Java SE 18.9(based on Java 9) will release as LTS version. In other words, the migration terms is about one year.

I have one question.
When the TERASOLUNA support Java 9(or 18.3+)?
I want to know the support plan. It is necessary information to consider or decide the Java version to use.
(I'll hope supporting as soon as possible)

Thanks.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0 (master)
- [ ] 5.3.1 (5.3.x)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- http://www.oracle.com/technetwork/jp/java/eol-135779.html
* #773

**Comment by yoshikawaa** [comment]
TERASOLUNA 5.5.1 will supports Java 11. Not support Java 9.
Thanks.
