### ISSUE TITLE
Upgrade to Spring IO Platform Brussels-SR5

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw#772]
## Description
Upgrade to current Spring IO Platform using Spring 4.
https://docs.spring.io/platform/docs/Brussels-SR5/reference/htmlsingle/

## Possible Solutions
Change version.
https://github.com/terasolunaorg/terasoluna-gfw/blob/0f4c27afb5742cea6e904fe7c8e583f7694b02b7/terasoluna-gfw-parent/pom.xml#L395

## Affects Version/s
- 5.4.0.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)

## Final Solution
See Possible Solutions.

## Migrating Guide
- [ ] Required

## Issue Links
- #741 
- #732

**Comment by kazuki43zoo** [comment]
:+1: 

I want to try early the snapshot version for 5.4.0 :)
