### ISSUE TITLE
Support JDK9 on Travis CI

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#773]
## Description
The Travis CI support a build using JDK9(Oracle JDK). See https://docs.travis-ci.com/user/reference/trusty/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-images .

## Possible Solutions

At first, upgrade some maven plugin to latest version.

* maven-surefire-plugin
* jacoco-maven-plugin
* maven-source-plugin
* maven-javadoc-plugin

At second, override the `java.version` ( `9` -> `9.0`) on maven-surefire-plugin. The `java.version` is `9` only on Travis CI. However, the `aspectj-weaver` expect `n.n` format like `1.8`, `9.0` and so on.  (This change is workaround. In [latest version](https://github.com/eclipse/org.aspectj/blob/b1ce395b9b55c74f9a6db9787ed9b382d022d710/util/src/org/aspectj/util/LangUtil.java#L76) will fix this issue)

At third, Add setting for skipping coverall on Java 9. (This change is a workaround for trautonen/coveralls-maven-plugin#112) 

At final, add `oraclejdk9` in `.travis.yml`

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.4.0 (master)
- [ ] 5.3.1 (5.3.x)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- #771

**Comment by yoshikawaa** [comment]
TERASOLUNA 5.5.1 will supports Java 11. Not support Java 9.
Thanks.
