### ISSUE TITLE
Can't validate SimpleI18nCodelist by @ExsitInCodeList

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/terasoluna-gfw#796]
## Description
Input check using `@ExsitInCodeList` on `SimpleI18nCodelist` always results in an input check error.
Please See Details terasolunaorg/guideline#3231

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.5.0 (master)
- [ ] 5.4.1 (5.4.x)

## Final Solution
(To be written later by project member)

## Migrating Guide
(To be selected later by project member)
- [ ] Required
- Not Required

## Issue Links
- https://github.com/terasolunaorg/terasoluna-gfw/issues/363

**Comment by btkitsunedukam** [comment]
https://github.com/terasolunaorg/terasoluna-gfw/issues/363 で対応する。

**Comment by yoshikawaa** [comment]
Fixed at #803 .
