### ISSUE TITLE
Upgrade to Spring IO Platform Cairo-SR1

### ISSUE THREAD

**Issue by btournc** [terasolunaorg/terasoluna-gfw#810]
## Description
Upgrade to current Spring IO Platform using Spring 5.
https://docs.spring.io/platform/docs/Cairo-SR1/reference/htmlsingle/

## Possible Solutions
Change version.

terasoluna-gfw/terasoluna-gfw-parent/pom.xml 

Line 395   <io.spring.platform.version>Brussels-SR5</io.spring.platform.version>  

## Affects Version/s
•5.5.0.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.0 (master)

## Final Solution
See Possible Solutions.

## Migrating Guide
- [ ] Required

## Issue Links
- #813

**Comment by yoshikawaa** [comment]
@hirakuriy 
Spring IO Platform Cairo SR2 has bean   released :exclamation: 
https://spring.io/blog/2018/06/18/spring-io-platform-cairo-sr2
