### ISSUE TITLE
Upgrade to  dozer 6.2

### ISSUE THREAD

**Issue by btournc** [terasolunaorg/terasoluna-gfw#823]
## Description
The following OSS's versions to upgrade.
https://mvnrepository.com/artifact/com.github.dozermapper/dozer-core

## Possible Solutions
none

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0 (master)

## Issue Links
- #731 
- #810

**Comment by hirakuriy** [comment]
@kazuki43zoo 
Thank you for your information.
This Dozer's upgrade will be mainly done for initial practical investigation of the impact associated with upgrading 5.x to 6.x .  So, based on the result, we will re-consider which version to use and upgrading timing.

**Comment by kazuki43zoo** [comment]
6.3 has been released.

**Comment by yoshikawaa** [comment]
@kazuki43zoo Thanks!
@hirakuriy  Let's upgrade to 6.3, I think there is no reason not to upgrade.

**Comment by hirakuriy** [comment]
@kazuki43zoo 
@yoshikawaa 
We'll upgrade Dozer's version to 6.3 in another issue.
