### ISSUE TITLE
Upgrade to dozer 6.x

### ISSUE THREAD

**Issue by btshuugna** [terasolunaorg/terasoluna-gfw#829]
## Description
The Dozer v6.x to upgrade.
See release note:
- https://github.com/DozerMapper/dozer/releases/tag/6.4.1
- https://github.com/DozerMapper/dozer/releases/tag/6.4.0
- https://github.com/DozerMapper/dozer/releases/tag/6.3.0
- https://github.com/DozerMapper/dozer/releases/tag/6.2.0

## Possible Solutions
none

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0 (master)

## Issue Links
- #731
- #823

**Comment by yoshikawaa** [comment]
Dozer 6.4.0 has bean released! https://github.com/DozerMapper/dozer/releases

**Comment by yoshikawaa** [comment]
See https://github.com/terasolunaorg/terasoluna-gfw/pull/831#pullrequestreview-146684612
