### ISSUE TITLE
f:query can not successfully take over properties of type Boolean

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw#846]
## Description
http://terasolunaorg.github.io/guideline/5.4.1.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.html#id7

`f:query` can not successfully take over properties of type Boolean.

For example, it's case of taking over the search condition.

* Search condition

```html
<form:radiobutton path="finished" value="" label="All" /> <!-- finished= -->
<form:radiobutton path="finished" value="true" label="Finished" /> <!-- finished=true -->
<form:radiobutton path="finished" value="false" label="Working" /> <!-- finished=false -->
```

* Form object

```java
public class Form {
  private Boolean finished;
}
```

* SQL(MyBatis Mapper)

```xml
<if test="condition.finished != null">
	AND finished = #{condition.finished}
</if>
```

* Taking over condition using `f:query`

```
<t:pagination page="${page}" criteriaQuery="${f:query(form)}"> <!-- _finished= -->
```

Spring MVC binds request parameter to Boolean property as follows:
* `finished=` -> `null` (Search condition)
* `_finished=` -> `false` (Taked over condition)

`f:query` does not play own role because the original search condition can not successfully take over.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.5.1.RELEASE

## Fix Version/s
- [x] 5.6.0 (master)

## Final Solution
(To be written later by project member)

## Migrating Guide
- [ ] Required

## Issue Links
- #XXX

**Comment by kazuki43zoo** [comment]
@yoshikawaa 

As workaround, we can use the special parameter for specifying a field default value that start with `!` (e.g. `!finished=`).

e.g.)

```
<t:pagination page="${page}" criteriaQuery="${f:query(form)}&!finished=" ..>
```

About the special parameter, please see the [`WebDataBinder`](https://github.com/spring-projects/spring-framework/blob/f5da737bd459a86a59c347040625715fcf55f57b/spring-web/src/main/java/org/springframework/web/bind/WebDataBinder.java#L208).

---

Would you report to the Spring JIRA? I will hope it! I prefer that a default value of `java.lang.Boolean` field is `null`.

**Comment by yoshikawaa** [comment]
@kazuki43zoo 
Thanks for your advice. I reported as [SPR-17513](https://jira.spring.io/browse/SPR-17513).

If forms have many `Boolean` properties, it is hard to build URL.
If we use `Boolean` and `boolean` consciously for the whole application, I think it may be more reasonable to extend `f:query` to change `Boolean` Empty Value (`_`) to Default Value (`!`).

**Comment by yoshikawaa** [comment]
As far as [SPR-17513#comment](https://jira.spring.io/browse/SPR-17513?focusedCommentId=163512&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-163512) and [Spring Reference#checkbox tag](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-view-jsp-formtaglib-checkboxtag) are concerned, `_finished=` to `false` is completely intentional behavior of Spring MVC.

It seems correct that `f:query` works as follows:
* Boolean `null` -> `finished=` or `!finished=`
* Boolean `false` -> `finished=false` or `_finished=`

> value of `!` and `_` parameters is anything ok.
