### ISSUE TITLE
jcl-over-slf4j not need

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#889]
## Description

Probably, the `jcl-over-slf4j` not need since Spring Framework 5.x. It can be replaced the `spring-jcl`. The `spring-jcl` supports bridging to an SLF4J based logging library(e.g. `logback`).

## Possible Solutions

Remove dependency the `jcl-over-slf4j`.

https://github.com/terasolunaorg/terasoluna-gfw/blob/0187e163a80fca3e8826fee2b8de8f4352761f63/terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml#L36-L39

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.6.0
- [x] 5.5.2

## Issue Links
- #827

**Comment by yoshikawaa** [comment]
@kazuki43zoo Thanks for your advice. Certainly `jcl-over-slf4j` is unnecessary

**Comment by yoshikawaa** [comment]
Note:
In a blank project, `dozer-core` or `tiles-core` transitively references `jcl-over-slf4j`.
