### ISSUE TITLE
Update SpringIOPlatform to Brusseles-SR17

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw#896]
## Description
Update SpringIOPlatform to Brusseles-SR17

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.2 (5.4.x)

## Issue Links
- #XXX

**Comment by btyanagawamg** [comment]
see https://github.com/terasolunaorg/terasoluna-gfw/pull/897#issuecomment-480149277

**Comment by btiwahorisu** [comment]
>see #897 (comment)  

Thank you. solved it in the next issue.
https://github.com/terasolunaorg/terasoluna-gfw/issues/898

**Comment by btiwahorisu** [comment]
As updated to `Brusseles-SR17`, I also update  `cargo version` .

**Comment by yoshikawaa** [comment]
Changes summary.
* Upgrade Spring IO Platform to Brusseles-SR17.
* Remove specific upgrade Spring Security OAuth2 to 2.0.17. -> #898 (correct incomplete changes)
* Downgrade Tomcat to 8.5.38 from managed 8.5.39. -> #902 (apply tomcat bugs)

Related changes summary.
* Upgrade MyBatis3 to 3.4.6. -> #904  (apply latest version for Spring 4 & Java 7)
