### ISSUE TITLE
Apply MyBatis 3.5.1 and MyBatis-Spring 2.0.1

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-gfw#900]
## Description

The MyBatis team has been released 1st maintenance version for fixing bugs(includes enhancements too) on mybatis 3.5 line and mybatis-spring 2.0 line.

* [MyBatis 3.5.1](https://github.com/mybatis/mybatis-3/releases/tag/mybatis-3.5.1)
* [MyBatis Spring 2.0.1](https://github.com/mybatis/spring/releases/tag/mybatis-spring-2.0.1)

## Possible Solutions

Please consider to apply latest maintenance version into master branch (next release).

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [ ] 5.6.0 (master)
- [ ] 5.5.2 (5.5.x)

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
@kazuki43zoo Thanks for the release report. We will apply 3.5.1 at next release (TERA 5.6.0, 5.5.2).

**Comment by kazuki43zoo** [comment]
Hi @yoshikawaa ,  The mybatis-spring 2.0.1 has known issue. please see [here](https://github.com/mybatis/spring/releases/tag/mybatis-spring-2.0.1). It will be resolved at 2.0.2.

**Comment by kazuki43zoo** [comment]
The mybatis-spring 2.0.2 will be release about July.
If you cannot wait until July, we can consider to ship it more early.

**Comment by kazuki43zoo** [comment]
Close because already applied.
