### ISSUE TITLE
Apply MyBatis 3.4.6 and MyBatis-Spring 1.3.2

### ISSUE THREAD

**Issue by hirakuriy** [terasolunaorg/terasoluna-gfw#904]
## Description
Apply MyBatis 3.4.6 and MyBatis-Spring 1.3.2

## Possible Solutions
Apply MyBatis 3.4.6 and MyBatis-Spring 1.3.2

## Affects Version/s
- 5.4.1.RELEASE
- 5.3.X.RELEASE

## Fix Version/s
- [x] 5.4.2 (5.4.x)

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
Note:
MyBatis 3.4.6 + MyBatis Spring 1.3.2 are latest versions for Spring 4 & Java 7.
TERASOLUNA 5.4.2 is last active maintained version for Spring 4 & Java 7.
