### ISSUE TITLE
[5.4.2.RELEASE] Upgrade to Tomcat 8.5.40

### ISSUE THREAD

**Issue by btiwahorisu** [terasolunaorg/terasoluna-gfw#907]
## Description
[Downgraded to `8.5.38`](https://github.com/terasolunaorg/terasoluna-gfw/issues/902) due to a [bug in tomcat 8.5.39](https://github.com/spring-projects/spring-boot/issues/16486), the above bug was resolved in 8.5.40.
https://github.com/spring-projects/spring-boot/issues/16504
Therefore, the version of tomcat is updated to `8.5.40`.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.x (5.4.2)

## Issue Links
- #902

**Comment by yoshikawaa** [comment]
Tomcat 8.5.38 was wrong. see http://tomcat.10.x6.nabble.com/catalina-pid-and-Tomcat-8-5-38-td5083159.html
