### ISSUE TITLE
Provide default validation message in ContributorValidationMessages.properties

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw#920]
## Description
Now, default messages of constraint annotation provided by common library is defined in ValidationMessages.properties of blank project.
However, this is **vulnerable to changes**, as you need to change the blank project whenever you change the common library. And we should also use a blank project to benefit from the default message.

In the first problem, **only one ValidationMessages.properties is allowed per application** in the Bean Validation specification (at least in the Hibernate Validator implementation).

-> See guideline [JP](http://terasolunaorg.github.io/guideline/5.5.1.RELEASE/ja/ArchitectureInDetail/WebApplicationDetail/Validation.html#validation-message-def).

To solve this, HibernateValidator provides [**ContributorValidationMessages.properties**](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_constraint_definitions_via_code_serviceloader_code) for defining default messages in libraries and submodules.

HibernateValidator resolves messages in the following order:

1. Only one ValidationMessages.properties
1. All of ContributorValidationMessages.properties
1. HibernateValidator default message ( org/hibernate/validator/ValidationMessages.properteis )

If don't use HibernateValidator, ContributorValidationMessages.properties is just ignored and does no harm.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.5.1.RELEASE

## Fix Version/s
- [x] 5.6.0 (master)

## Issue Links
- #256

**Comment by takahashihrzg** [comment]
@yoshikawaa
ご要望に沿ってこちらで。

> これはレビューコメントではないので共通ライブラリのIssueで議論してほしいです。
>> 5.2はリリースの予定がないので、ここは5.6.0と書くのが正しいと思います。
>> (5.6.0はTERAとしてはガイドが出ないので周知の面では弱いですが、共通ライブラリはMacchinetta向けにリリースすることになるはずなので、間違ったことは言わずに済む)

という所については、このPR内容に対するコメントとその背景なのでレビューコメントだと思っていますがいかがでしょう。

一方で、

> また、わざわざ5.4.2にバックポートする中身でも無いと思いますが、いかがでしょう

こちらの内容はこのPRの元になったIssueの対応範囲に関することなので、確かにIssueで議論すべき中身だと思います。

以下の理解で良いでしょうか。

- PRにコメントする内容は、そのPRが対応しようとしている範囲についてだけに留める
- それ以外の内容は、Issueに記載する

> さらに、「5.5.2はリリースの予定がない」は政治的な話になるので、Issueではなく内部で議論すべきことな気もします。

プライベートなリポジトリなので、特に、「政治的な話をすべきでない」というような制約はないと考えています。
その上で、議論がIssueとそこではない所(Teamsとか)で分散して行われると経緯が追いづらくなるので、これは避けたほうが良いと考えます。

> ちなみに「わざわざ5.4.2にバックポートする中身でも無い」の意図は何でしょう？

こちらについては、軽微かつマイグレ等があればユーザも追従可能だとは思いますが、
デフォルトメッセージの提供箇所が変わるのは一応、破壊的な変更と言える気がするのでどうなんだろうと思っているのと
仮に入れたとすると、5.4.3、5.6.0以降では対応しているけど、5.5.1では対応していない、
というように、バージョニングでみると単に「～以降からは変更しているよ」と言えない状況になるので、混乱を招くかなと。

ここらへんを押しても、メリットがあるからやったほうが良いと言う事ならバックポートすべきだと思います。

**Comment by yoshikawaa** [comment]
#### Will it be a disruptive change?
Do not assume that disruptive changes will "prevent existing functionality".
1. If a default message is listed in ValidationMessages.properties, this takes precedence.
-> The message definition of the existing blank project has priority.
2. If there is no default message in ValidationMessages.properties, the default message in ContributorValidationMessages.properties is used.
-> If the message definition of an existing blank project has been deleted, the default message will be displayed if the message key has been displayed.
-> The message key is displayed as an application bug, so there is no reason to protect this behavior

#### Supported version
Assuming that it will not be a disruptive change, messages will not be changed without special migration, so it will be improved rather than adding new functions.
As an improvement, it is assumed that it will be released as a maintenance version.
