### ISSUE TITLE
Updating self defined libraries

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw#933]
## Description
Updating self defined libraries.

## Possible Solutions
Update for improvement
* spring-security-oauth2
* mybatis
* mybatis-spring
* dozer-core
* dozer-spring4

Updates to address vulnerabilities
* commons-beanutils
* poi

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.6.0 (master)
- [ ] ~~5.5.2 (5.5.x)~~

## Issue Links
- #XXX

**Comment by kazuki43zoo** [comment]
Could you tell me a limit date for apply this issue ? In current plan, the mybatis(3.5.5) and mybatis-spring(2.0.5) will be released at this weekend or next weekend.

**Comment by yoshikawaa** [comment]
@kazuki43zoo 
Thank you for the mybatis release date announcement.
But unfortunately, the roadmap for 5.6.0 are almost done, and we can't upgrade any of the library without a serious reason. The latest MyBatis will be adopted in 5.6.1 or 5.7.0.

Regards.

**Comment by kazuki43zoo** [comment]
@yoshidatkw 

Thanks for your quick reaction. OK I understand.

**Comment by btkobayashirun** [comment]
Closed because 5.5.2 is outside the scope of modification.
