### ISSUE TITLE
H2 sequence specifications changed

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw#936]
## Description
If #935 is supported, the test will fail due to the H2 specification change.

>Current value may only be requested after generation of the sequence value in the current session. 

https://h2database.com/html/functions.html#currval

## Possible Solutions
Get current value after generation.

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.6.0 (master)

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
If you require current value without `NEXT`, you can probably use [INFORMATION_SCHEMA.SEQUENCE](https://www.h2database.com/html/systemtables.html)
