### ISSUE TITLE
Fixed warning about using deprecated methods in unit tests on JDK11

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/terasoluna-gfw#965]
## Description
The following warning occurs when running unit test on JDK11.

``` java
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ terasoluna-gfw-string ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /home/travis/build/terasolunaorg/terasoluna-gfw/terasoluna-gfw-common-libraries/terasoluna-gfw-string/target/test-classes
[WARNING] /home/travis/build/terasolunaorg/terasoluna-gfw/terasoluna-gfw-common-libraries/terasoluna-gfw-string/src/test/java/org/terasoluna/gfw/common/fullhalf/DefaultFullHalfTest.java: /home/travis/build/terasolunaorg/terasoluna-gfw/terasoluna-gfw-common-libraries/terasoluna-gfw-string/src/test/java/org/terasoluna/gfw/common/fullhalf/DefaultFullHalfTest.java uses or overrides a deprecated API.
[WARNING] /home/travis/build/terasolunaorg/terasoluna-gfw/terasoluna-gfw-common-libraries/terasoluna-gfw-string/src/test/java/org/terasoluna/gfw/common/fullhalf/DefaultFullHalfTest.java: Recompile with -Xlint:deprecation for details.
```

The list of target classes is as follows.

* `DateConvertUtilsTest.java`
* `HtmlEscapeUtilsTest.java`
* `JspTagUtilsTest`
* `DefaultFullHalfTest.java`
* `ConstraintValidatorsUtilsTest.java`
* `CodePoints.java`

## Possible Solutions
`CodePoints.java`

reference : [Class#newInstance()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html#newInstance())

Deprecated code
``` java 
    T codePoints = clazz.newInstance();
```

Correction example
``` java
    T codePoints = clazz.getDeclaredConstructor().newInstance()
```

---
Others

reference : [AccessibleObject#isAccessible()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/AccessibleObject.html#isAccessible())
※`canAccess()` method was added in JDK9.

Deprecated code
``` java 
    assertThat(constructor.isAccessible(), is(false));
```

Correction example
``` java
    assertThat(constructor.canAccess(null), is(false));
```

## Affects Version/s
- 5.X.X.RELEASE

## Fix Version/s
- [x] 5.6.0 (master)

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
#### `isAccessible` to  `canAccess`
`canAccess` method is Introduced in JDK 9.
In order to support JDK 8, terasoluna-gfw will not accept this change.

What about suppressing warnings using `@SuppressWarning("deprecation")`?
・ In JDK 11, warning is suppressed. 
・ In JDK 8, a warning is output.

As a result, it makes sense to make no changes.
