### ISSUE TITLE
Apply Dozer 6.5.2

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-gfw#998]
## Description

https://github.com/DozerMapper/dozer/releases/tag/v6.5.2
Dozer 6.5.2 has bean released.

## Possible Solution

Apply curernt Dozer.
* `dozer-core`: 6.5.2
* `dozer-spring4`: 6.5.2

## Affect versions

- 5.8.0.RELEASE

## Issue links

- #xx

**Comment by yoshikawaa** [comment]
https://mvnrepository.com/artifact/com.github.dozermapper/dozer-core
dozer-core 6.5.1 released on Github but not yet deployed on Maven Central.

**Comment by btkatoufm** [comment]
>https://mvnrepository.com/artifact/com.github.dozermapper/dozer-core
dozer-core 6.5.1 released on Github but not yet deployed on Maven Central.

5.6.2 has been deployed to Maven Central.
https://mvnrepository.com/artifact/com.github.dozermapper/dozer-core/6.5.2
https://mvnrepository.com/artifact/com.github.dozermapper/dozer-spring4/6.5.2
